syntax = "proto3";

package chat.v1;

import "buf/validate/validate.proto";

service DirectMessageService {
  rpc ListDirectMessages(ListDirectMessagesRequest) returns (ListDirectMessagesResponse);
  rpc CreateDirectMessage(CreateDirectMessageRequest) returns (CreateDirectMessageResponse);
  rpc CreateGroupDirectMessage(CreateGroupDirectMessageRequest) returns (CreateGroupDirectMessageResponse);
}

enum DirectMessageType {
  DIRECT_MESSAGE_TYPE_UNSPECIFIED = 0;
  DIRECT_MESSAGE_TYPE_DM = 1;
  DIRECT_MESSAGE_TYPE_GROUP_DM = 2;
}

message DirectMessage {
  string id = 1;
  DirectMessageType type = 5;
  repeated DirectMessageMember members = 6;
  bool is_starred = 9;
  bool is_muted = 10;
  // ListDirectMessages でのみ設定される
  int32 unread_count = 11;
}

message DirectMessageMember {
  string user_id = 1;
  string display_name = 2;
  optional string avatar_url = 3;
}

message ListDirectMessagesRequest {
  string workspace_id = 1 [(buf.validate.field).string.min_len = 1];
}

message ListDirectMessagesResponse {
  repeated DirectMessage direct_messages = 1;
}

message CreateDirectMessageRequest {
  string workspace_id = 1 [(buf.validate.field).string.min_len = 1];
  string user_id = 2 [(buf.validate.field).string.uuid = true];
}

message CreateDirectMessageResponse {
  DirectMessage direct_message = 1;
}

message CreateGroupDirectMessageRequest {
  string workspace_id = 1 [(buf.validate.field).string.min_len = 1];
  repeated string user_ids = 2 [(buf.validate.field).repeated = {
    min_items: 2
    max_items: 9
    items: {
      string: {uuid: true}
    }
  }];
}

message CreateGroupDirectMessageResponse {
  DirectMessage direct_message = 1;
}
