syntax = "proto3";

package chat.v1;

import "buf/validate/validate.proto";
import "chat/v1/message.proto";

service PinService {
  rpc ListPins(ListPinsRequest) returns (ListPinsResponse);
  rpc CreatePin(CreatePinRequest) returns (CreatePinResponse);
  rpc DeletePin(DeletePinRequest) returns (DeletePinResponse);
}

message ListPinsRequest {
  string channel_id = 1 [(buf.validate.field).string.uuid = true];
}

// ピン留めした新しい順。ピン留めの情報は Message.pin に入る
message ListPinsResponse {
  repeated Message messages = 1;
}

message CreatePinRequest {
  string channel_id = 1 [(buf.validate.field).string.uuid = true];
  string message_id = 2 [(buf.validate.field).string.uuid = true];
}

message CreatePinResponse {}

message DeletePinRequest {
  string channel_id = 1 [(buf.validate.field).string.uuid = true];
  string message_id = 2 [(buf.validate.field).string.uuid = true];
}

message DeletePinResponse {}
