syntax = "proto3";

package chat.v1;

import "buf/validate/validate.proto";

service ReactionService {
  rpc AddReaction(AddReactionRequest) returns (AddReactionResponse);
  rpc RemoveReaction(RemoveReactionRequest) returns (RemoveReactionResponse);
}

message AddReactionRequest {
  string message_id = 1 [(buf.validate.field).string.uuid = true];
  string emoji = 2 [(buf.validate.field).string.min_len = 1];
}

message AddReactionResponse {}

message RemoveReactionRequest {
  string message_id = 1 [(buf.validate.field).string.uuid = true];
  string emoji = 2 [(buf.validate.field).string.min_len = 1];
}

message RemoveReactionResponse {}
