// Code generated by ent, DO NOT EDIT.

package userpreference

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userpreference type in the database.
	Label = "user_preference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldThemeHue holds the string denoting the theme_hue field in the database.
	FieldThemeHue = "theme_hue"
	// FieldThemeChroma holds the string denoting the theme_chroma field in the database.
	FieldThemeChroma = "theme_chroma"
	// FieldThemeSidebar holds the string denoting the theme_sidebar field in the database.
	FieldThemeSidebar = "theme_sidebar"
	// FieldColorMode holds the string denoting the color_mode field in the database.
	FieldColorMode = "color_mode"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldNotificationLevel holds the string denoting the notification_level field in the database.
	FieldNotificationLevel = "notification_level"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldTimezoneAutoUpdate holds the string denoting the timezone_auto_update field in the database.
	FieldTimezoneAutoUpdate = "timezone_auto_update"
	// FieldChannelSortOrder holds the string denoting the channel_sort_order field in the database.
	FieldChannelSortOrder = "channel_sort_order"
	// FieldHideJoinMessages holds the string denoting the hide_join_messages field in the database.
	FieldHideJoinMessages = "hide_join_messages"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userpreference in the database.
	Table = "user_preference"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_preference"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userpreference fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldThemeHue,
	FieldThemeChroma,
	FieldThemeSidebar,
	FieldColorMode,
	FieldLocale,
	FieldNotificationLevel,
	FieldTimezone,
	FieldTimezoneAutoUpdate,
	FieldChannelSortOrder,
	FieldHideJoinMessages,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ThemeSidebar defines the type for the "theme_sidebar" enum field.
type ThemeSidebar string

// ThemeSidebar values.
const (
	ThemeSidebarTinted ThemeSidebar = "tinted"
	ThemeSidebarLight  ThemeSidebar = "light"
)

func (ts ThemeSidebar) String() string {
	return string(ts)
}

// ThemeSidebarValidator is a validator for the "theme_sidebar" field enum values. It is called by the builders before save.
func ThemeSidebarValidator(ts ThemeSidebar) error {
	switch ts {
	case ThemeSidebarTinted, ThemeSidebarLight:
		return nil
	default:
		return fmt.Errorf("userpreference: invalid enum value for theme_sidebar field: %q", ts)
	}
}

// ColorMode defines the type for the "color_mode" enum field.
type ColorMode string

// ColorMode values.
const (
	ColorModeLight  ColorMode = "light"
	ColorModeDark   ColorMode = "dark"
	ColorModeSystem ColorMode = "system"
)

func (cm ColorMode) String() string {
	return string(cm)
}

// ColorModeValidator is a validator for the "color_mode" field enum values. It is called by the builders before save.
func ColorModeValidator(cm ColorMode) error {
	switch cm {
	case ColorModeLight, ColorModeDark, ColorModeSystem:
		return nil
	default:
		return fmt.Errorf("userpreference: invalid enum value for color_mode field: %q", cm)
	}
}

// NotificationLevel defines the type for the "notification_level" enum field.
type NotificationLevel string

// NotificationLevel values.
const (
	NotificationLevelAll      NotificationLevel = "all"
	NotificationLevelMentions NotificationLevel = "mentions"
	NotificationLevelNone     NotificationLevel = "none"
)

func (nl NotificationLevel) String() string {
	return string(nl)
}

// NotificationLevelValidator is a validator for the "notification_level" field enum values. It is called by the builders before save.
func NotificationLevelValidator(nl NotificationLevel) error {
	switch nl {
	case NotificationLevelAll, NotificationLevelMentions, NotificationLevelNone:
		return nil
	default:
		return fmt.Errorf("userpreference: invalid enum value for notification_level field: %q", nl)
	}
}

// ChannelSortOrder defines the type for the "channel_sort_order" enum field.
type ChannelSortOrder string

// ChannelSortOrder values.
const (
	ChannelSortOrderDefault        ChannelSortOrder = "default"
	ChannelSortOrderRecentActivity ChannelSortOrder = "recent_activity"
)

func (cso ChannelSortOrder) String() string {
	return string(cso)
}

// ChannelSortOrderValidator is a validator for the "channel_sort_order" field enum values. It is called by the builders before save.
func ChannelSortOrderValidator(cso ChannelSortOrder) error {
	switch cso {
	case ChannelSortOrderDefault, ChannelSortOrderRecentActivity:
		return nil
	default:
		return fmt.Errorf("userpreference: invalid enum value for channel_sort_order field: %q", cso)
	}
}

// OrderOption defines the ordering options for the UserPreference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByThemeHue orders the results by the theme_hue field.
func ByThemeHue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThemeHue, opts...).ToFunc()
}

// ByThemeChroma orders the results by the theme_chroma field.
func ByThemeChroma(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThemeChroma, opts...).ToFunc()
}

// ByThemeSidebar orders the results by the theme_sidebar field.
func ByThemeSidebar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThemeSidebar, opts...).ToFunc()
}

// ByColorMode orders the results by the color_mode field.
func ByColorMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColorMode, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByNotificationLevel orders the results by the notification_level field.
func ByNotificationLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotificationLevel, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByTimezoneAutoUpdate orders the results by the timezone_auto_update field.
func ByTimezoneAutoUpdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezoneAutoUpdate, opts...).ToFunc()
}

// ByChannelSortOrder orders the results by the channel_sort_order field.
func ByChannelSortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelSortOrder, opts...).ToFunc()
}

// ByHideJoinMessages orders the results by the hide_join_messages field.
func ByHideJoinMessages(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHideJoinMessages, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
