// Code generated by ent, DO NOT EDIT.

package attachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMessageID, v))
}

// UploaderID applies equality check predicate on the "uploader_id" field. It's identical to UploaderIDEQ.
func UploaderID(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldUploaderID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldChannelID, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldFileName, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldSizeBytes, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldHeight, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldDurationSeconds, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldStorageKey, v))
}

// ThumbnailStorageKey applies equality check predicate on the "thumbnail_storage_key" field. It's identical to ThumbnailStorageKeyEQ.
func ThumbnailStorageKey(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailStorageKey, v))
}

// ThumbnailWidth applies equality check predicate on the "thumbnail_width" field. It's identical to ThumbnailWidthEQ.
func ThumbnailWidth(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailWidth, v))
}

// ThumbnailHeight applies equality check predicate on the "thumbnail_height" field. It's identical to ThumbnailHeightEQ.
func ThumbnailHeight(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailHeight, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldStatus, v))
}

// UploadedAt applies equality check predicate on the "uploaded_at" field. It's identical to UploadedAtEQ.
func UploadedAt(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldUploadedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldCreatedAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldMessageID))
}

// UploaderIDEQ applies the EQ predicate on the "uploader_id" field.
func UploaderIDEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldUploaderID, v))
}

// UploaderIDNEQ applies the NEQ predicate on the "uploader_id" field.
func UploaderIDNEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldUploaderID, v))
}

// UploaderIDIn applies the In predicate on the "uploader_id" field.
func UploaderIDIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldUploaderID, vs...))
}

// UploaderIDNotIn applies the NotIn predicate on the "uploader_id" field.
func UploaderIDNotIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldUploaderID, vs...))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...uuid.UUID) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldChannelID, vs...))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldFileName, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldSizeBytes, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldHeight))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v float64) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldDurationSeconds, v))
}

// DurationSecondsIsNil applies the IsNil predicate on the "duration_seconds" field.
func DurationSecondsIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldDurationSeconds))
}

// DurationSecondsNotNil applies the NotNil predicate on the "duration_seconds" field.
func DurationSecondsNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldDurationSeconds))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldStorageKey, v))
}

// ThumbnailStorageKeyEQ applies the EQ predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyNEQ applies the NEQ predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyIn applies the In predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldThumbnailStorageKey, vs...))
}

// ThumbnailStorageKeyNotIn applies the NotIn predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldThumbnailStorageKey, vs...))
}

// ThumbnailStorageKeyGT applies the GT predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyGTE applies the GTE predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyLT applies the LT predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyLTE applies the LTE predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyContains applies the Contains predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyHasPrefix applies the HasPrefix predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyHasSuffix applies the HasSuffix predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyIsNil applies the IsNil predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldThumbnailStorageKey))
}

// ThumbnailStorageKeyNotNil applies the NotNil predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldThumbnailStorageKey))
}

// ThumbnailStorageKeyEqualFold applies the EqualFold predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldThumbnailStorageKey, v))
}

// ThumbnailStorageKeyContainsFold applies the ContainsFold predicate on the "thumbnail_storage_key" field.
func ThumbnailStorageKeyContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldThumbnailStorageKey, v))
}

// ThumbnailWidthEQ applies the EQ predicate on the "thumbnail_width" field.
func ThumbnailWidthEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailWidth, v))
}

// ThumbnailWidthNEQ applies the NEQ predicate on the "thumbnail_width" field.
func ThumbnailWidthNEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldThumbnailWidth, v))
}

// ThumbnailWidthIn applies the In predicate on the "thumbnail_width" field.
func ThumbnailWidthIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldThumbnailWidth, vs...))
}

// ThumbnailWidthNotIn applies the NotIn predicate on the "thumbnail_width" field.
func ThumbnailWidthNotIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldThumbnailWidth, vs...))
}

// ThumbnailWidthGT applies the GT predicate on the "thumbnail_width" field.
func ThumbnailWidthGT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldThumbnailWidth, v))
}

// ThumbnailWidthGTE applies the GTE predicate on the "thumbnail_width" field.
func ThumbnailWidthGTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldThumbnailWidth, v))
}

// ThumbnailWidthLT applies the LT predicate on the "thumbnail_width" field.
func ThumbnailWidthLT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldThumbnailWidth, v))
}

// ThumbnailWidthLTE applies the LTE predicate on the "thumbnail_width" field.
func ThumbnailWidthLTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldThumbnailWidth, v))
}

// ThumbnailWidthIsNil applies the IsNil predicate on the "thumbnail_width" field.
func ThumbnailWidthIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldThumbnailWidth))
}

// ThumbnailWidthNotNil applies the NotNil predicate on the "thumbnail_width" field.
func ThumbnailWidthNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldThumbnailWidth))
}

// ThumbnailHeightEQ applies the EQ predicate on the "thumbnail_height" field.
func ThumbnailHeightEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldThumbnailHeight, v))
}

// ThumbnailHeightNEQ applies the NEQ predicate on the "thumbnail_height" field.
func ThumbnailHeightNEQ(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldThumbnailHeight, v))
}

// ThumbnailHeightIn applies the In predicate on the "thumbnail_height" field.
func ThumbnailHeightIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldThumbnailHeight, vs...))
}

// ThumbnailHeightNotIn applies the NotIn predicate on the "thumbnail_height" field.
func ThumbnailHeightNotIn(vs ...int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldThumbnailHeight, vs...))
}

// ThumbnailHeightGT applies the GT predicate on the "thumbnail_height" field.
func ThumbnailHeightGT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldThumbnailHeight, v))
}

// ThumbnailHeightGTE applies the GTE predicate on the "thumbnail_height" field.
func ThumbnailHeightGTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldThumbnailHeight, v))
}

// ThumbnailHeightLT applies the LT predicate on the "thumbnail_height" field.
func ThumbnailHeightLT(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldThumbnailHeight, v))
}

// ThumbnailHeightLTE applies the LTE predicate on the "thumbnail_height" field.
func ThumbnailHeightLTE(v int32) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldThumbnailHeight, v))
}

// ThumbnailHeightIsNil applies the IsNil predicate on the "thumbnail_height" field.
func ThumbnailHeightIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldThumbnailHeight))
}

// ThumbnailHeightNotNil applies the NotNil predicate on the "thumbnail_height" field.
func ThumbnailHeightNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldThumbnailHeight))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldStatus, v))
}

// UploadedAtEQ applies the EQ predicate on the "uploaded_at" field.
func UploadedAtEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldUploadedAt, v))
}

// UploadedAtNEQ applies the NEQ predicate on the "uploaded_at" field.
func UploadedAtNEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldUploadedAt, v))
}

// UploadedAtIn applies the In predicate on the "uploaded_at" field.
func UploadedAtIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldUploadedAt, vs...))
}

// UploadedAtNotIn applies the NotIn predicate on the "uploaded_at" field.
func UploadedAtNotIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldUploadedAt, vs...))
}

// UploadedAtGT applies the GT predicate on the "uploaded_at" field.
func UploadedAtGT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldUploadedAt, v))
}

// UploadedAtGTE applies the GTE predicate on the "uploaded_at" field.
func UploadedAtGTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldUploadedAt, v))
}

// UploadedAtLT applies the LT predicate on the "uploaded_at" field.
func UploadedAtLT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldUploadedAt, v))
}

// UploadedAtLTE applies the LTE predicate on the "uploaded_at" field.
func UploadedAtLTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldUploadedAt, v))
}

// UploadedAtIsNil applies the IsNil predicate on the "uploaded_at" field.
func UploadedAtIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldUploadedAt))
}

// UploadedAtNotNil applies the NotNil predicate on the "uploaded_at" field.
func UploadedAtNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldUploadedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Attachment {
	return predicate.Attachment(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploader applies the HasEdge predicate on the "uploader" edge.
func HasUploader() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UploaderTable, UploaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploaderWith applies the HasEdge predicate on the "uploader" edge with a given conditions (other predicates).
func HasUploaderWith(preds ...predicate.User) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newUploaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.NotPredicates(p))
}
