run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/example/chat

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
