FROM golang:1.25-alpine

# Install Atlas CLI
RUN apk add --no-cache curl git && \
    curl -sSf https://atlasgo.sh | sh

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Run with air for hot reload
CMD ["air", "-c", "air.toml"]
