// Code generated by ent, DO NOT EDIT.

package threadreadstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLTE(FieldID, id))
}

// LastReadAt applies equality check predicate on the "last_read_at" field. It's identical to LastReadAtEQ.
func LastReadAt(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldLastReadAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastReadAtEQ applies the EQ predicate on the "last_read_at" field.
func LastReadAtEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldLastReadAt, v))
}

// LastReadAtNEQ applies the NEQ predicate on the "last_read_at" field.
func LastReadAtNEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNEQ(FieldLastReadAt, v))
}

// LastReadAtIn applies the In predicate on the "last_read_at" field.
func LastReadAtIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldIn(FieldLastReadAt, vs...))
}

// LastReadAtNotIn applies the NotIn predicate on the "last_read_at" field.
func LastReadAtNotIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNotIn(FieldLastReadAt, vs...))
}

// LastReadAtGT applies the GT predicate on the "last_read_at" field.
func LastReadAtGT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGT(FieldLastReadAt, v))
}

// LastReadAtGTE applies the GTE predicate on the "last_read_at" field.
func LastReadAtGTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGTE(FieldLastReadAt, v))
}

// LastReadAtLT applies the LT predicate on the "last_read_at" field.
func LastReadAtLT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLT(FieldLastReadAt, v))
}

// LastReadAtLTE applies the LTE predicate on the "last_read_at" field.
func LastReadAtLTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLTE(FieldLastReadAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ThreadReadState {
	return predicate.ThreadReadState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ThreadReadState {
	return predicate.ThreadReadState(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasThread applies the HasEdge predicate on the "thread" edge.
func HasThread() predicate.ThreadReadState {
	return predicate.ThreadReadState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ThreadTable, ThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThreadWith applies the HasEdge predicate on the "thread" edge with a given conditions (other predicates).
func HasThreadWith(preds ...predicate.Message) predicate.ThreadReadState {
	return predicate.ThreadReadState(func(s *sql.Selector) {
		step := newThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ThreadReadState) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ThreadReadState) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ThreadReadState) predicate.ThreadReadState {
	return predicate.ThreadReadState(sql.NotPredicates(p))
}
