// Code generated by ent, DO NOT EDIT.

package linkpreviewyoutube

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLTE(FieldID, id))
}

// LinkPreviewID applies equality check predicate on the "link_preview_id" field. It's identical to LinkPreviewIDEQ.
func LinkPreviewID(v uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldLinkPreviewID, v))
}

// VideoID applies equality check predicate on the "video_id" field. It's identical to VideoIDEQ.
func VideoID(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldVideoID, v))
}

// ChannelName applies equality check predicate on the "channel_name" field. It's identical to ChannelNameEQ.
func ChannelName(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldChannelName, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldDurationSeconds, v))
}

// LinkPreviewIDEQ applies the EQ predicate on the "link_preview_id" field.
func LinkPreviewIDEQ(v uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldLinkPreviewID, v))
}

// LinkPreviewIDNEQ applies the NEQ predicate on the "link_preview_id" field.
func LinkPreviewIDNEQ(v uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNEQ(FieldLinkPreviewID, v))
}

// LinkPreviewIDIn applies the In predicate on the "link_preview_id" field.
func LinkPreviewIDIn(vs ...uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIn(FieldLinkPreviewID, vs...))
}

// LinkPreviewIDNotIn applies the NotIn predicate on the "link_preview_id" field.
func LinkPreviewIDNotIn(vs ...uuid.UUID) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotIn(FieldLinkPreviewID, vs...))
}

// VideoIDEQ applies the EQ predicate on the "video_id" field.
func VideoIDEQ(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldVideoID, v))
}

// VideoIDNEQ applies the NEQ predicate on the "video_id" field.
func VideoIDNEQ(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNEQ(FieldVideoID, v))
}

// VideoIDIn applies the In predicate on the "video_id" field.
func VideoIDIn(vs ...string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIn(FieldVideoID, vs...))
}

// VideoIDNotIn applies the NotIn predicate on the "video_id" field.
func VideoIDNotIn(vs ...string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotIn(FieldVideoID, vs...))
}

// VideoIDGT applies the GT predicate on the "video_id" field.
func VideoIDGT(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGT(FieldVideoID, v))
}

// VideoIDGTE applies the GTE predicate on the "video_id" field.
func VideoIDGTE(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGTE(FieldVideoID, v))
}

// VideoIDLT applies the LT predicate on the "video_id" field.
func VideoIDLT(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLT(FieldVideoID, v))
}

// VideoIDLTE applies the LTE predicate on the "video_id" field.
func VideoIDLTE(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLTE(FieldVideoID, v))
}

// VideoIDContains applies the Contains predicate on the "video_id" field.
func VideoIDContains(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldContains(FieldVideoID, v))
}

// VideoIDHasPrefix applies the HasPrefix predicate on the "video_id" field.
func VideoIDHasPrefix(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldHasPrefix(FieldVideoID, v))
}

// VideoIDHasSuffix applies the HasSuffix predicate on the "video_id" field.
func VideoIDHasSuffix(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldHasSuffix(FieldVideoID, v))
}

// VideoIDEqualFold applies the EqualFold predicate on the "video_id" field.
func VideoIDEqualFold(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEqualFold(FieldVideoID, v))
}

// VideoIDContainsFold applies the ContainsFold predicate on the "video_id" field.
func VideoIDContainsFold(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldContainsFold(FieldVideoID, v))
}

// ChannelNameEQ applies the EQ predicate on the "channel_name" field.
func ChannelNameEQ(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldChannelName, v))
}

// ChannelNameNEQ applies the NEQ predicate on the "channel_name" field.
func ChannelNameNEQ(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNEQ(FieldChannelName, v))
}

// ChannelNameIn applies the In predicate on the "channel_name" field.
func ChannelNameIn(vs ...string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIn(FieldChannelName, vs...))
}

// ChannelNameNotIn applies the NotIn predicate on the "channel_name" field.
func ChannelNameNotIn(vs ...string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotIn(FieldChannelName, vs...))
}

// ChannelNameGT applies the GT predicate on the "channel_name" field.
func ChannelNameGT(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGT(FieldChannelName, v))
}

// ChannelNameGTE applies the GTE predicate on the "channel_name" field.
func ChannelNameGTE(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGTE(FieldChannelName, v))
}

// ChannelNameLT applies the LT predicate on the "channel_name" field.
func ChannelNameLT(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLT(FieldChannelName, v))
}

// ChannelNameLTE applies the LTE predicate on the "channel_name" field.
func ChannelNameLTE(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLTE(FieldChannelName, v))
}

// ChannelNameContains applies the Contains predicate on the "channel_name" field.
func ChannelNameContains(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldContains(FieldChannelName, v))
}

// ChannelNameHasPrefix applies the HasPrefix predicate on the "channel_name" field.
func ChannelNameHasPrefix(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldHasPrefix(FieldChannelName, v))
}

// ChannelNameHasSuffix applies the HasSuffix predicate on the "channel_name" field.
func ChannelNameHasSuffix(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldHasSuffix(FieldChannelName, v))
}

// ChannelNameIsNil applies the IsNil predicate on the "channel_name" field.
func ChannelNameIsNil() predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIsNull(FieldChannelName))
}

// ChannelNameNotNil applies the NotNil predicate on the "channel_name" field.
func ChannelNameNotNil() predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotNull(FieldChannelName))
}

// ChannelNameEqualFold applies the EqualFold predicate on the "channel_name" field.
func ChannelNameEqualFold(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEqualFold(FieldChannelName, v))
}

// ChannelNameContainsFold applies the ContainsFold predicate on the "channel_name" field.
func ChannelNameContainsFold(v string) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldContainsFold(FieldChannelName, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int32) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldLTE(FieldDurationSeconds, v))
}

// DurationSecondsIsNil applies the IsNil predicate on the "duration_seconds" field.
func DurationSecondsIsNil() predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldIsNull(FieldDurationSeconds))
}

// DurationSecondsNotNil applies the NotNil predicate on the "duration_seconds" field.
func DurationSecondsNotNil() predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.FieldNotNull(FieldDurationSeconds))
}

// HasLinkPreview applies the HasEdge predicate on the "link_preview" edge.
func HasLinkPreview() predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, LinkPreviewTable, LinkPreviewColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinkPreviewWith applies the HasEdge predicate on the "link_preview" edge with a given conditions (other predicates).
func HasLinkPreviewWith(preds ...predicate.LinkPreview) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(func(s *sql.Selector) {
		step := newLinkPreviewStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LinkPreviewYoutube) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LinkPreviewYoutube) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LinkPreviewYoutube) predicate.LinkPreviewYoutube {
	return predicate.LinkPreviewYoutube(sql.NotPredicates(p))
}
