// Code generated by ent, DO NOT EDIT.

package linkpreviewxpost

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the linkpreviewxpost type in the database.
	Label = "link_preview_xpost"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLinkPreviewID holds the string denoting the link_preview_id field in the database.
	FieldLinkPreviewID = "link_preview_id"
	// FieldAuthorName holds the string denoting the author_name field in the database.
	FieldAuthorName = "author_name"
	// FieldAuthorHandle holds the string denoting the author_handle field in the database.
	FieldAuthorHandle = "author_handle"
	// EdgeLinkPreview holds the string denoting the link_preview edge name in mutations.
	EdgeLinkPreview = "link_preview"
	// Table holds the table name of the linkpreviewxpost in the database.
	Table = "link_preview_x_post"
	// LinkPreviewTable is the table that holds the link_preview relation/edge.
	LinkPreviewTable = "link_preview_x_post"
	// LinkPreviewInverseTable is the table name for the LinkPreview entity.
	// It exists in this package in order to avoid circular dependency with the "linkpreview" package.
	LinkPreviewInverseTable = "link_preview"
	// LinkPreviewColumn is the table column denoting the link_preview relation/edge.
	LinkPreviewColumn = "link_preview_id"
)

// Columns holds all SQL columns for linkpreviewxpost fields.
var Columns = []string{
	FieldID,
	FieldLinkPreviewID,
	FieldAuthorName,
	FieldAuthorHandle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LinkPreviewXPost queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLinkPreviewID orders the results by the link_preview_id field.
func ByLinkPreviewID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkPreviewID, opts...).ToFunc()
}

// ByAuthorName orders the results by the author_name field.
func ByAuthorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorName, opts...).ToFunc()
}

// ByAuthorHandle orders the results by the author_handle field.
func ByAuthorHandle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorHandle, opts...).ToFunc()
}

// ByLinkPreviewField orders the results by link_preview field.
func ByLinkPreviewField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinkPreviewStep(), sql.OrderByField(field, opts...))
	}
}
func newLinkPreviewStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinkPreviewInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, LinkPreviewTable, LinkPreviewColumn),
	)
}
