// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/channellink"
	"github.com/newt239/chat/ent/user"
)

// ChannelLink is the model entity for the ChannelLink schema.
type ChannelLink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelLinkQuery when eager-loading is set.
	Edges                   ChannelLinkEdges `json:"edges"`
	channel_link_channel    *uuid.UUID
	channel_link_created_by *uuid.UUID
	selectValues            sql.SelectValues
}

// ChannelLinkEdges holds the relations/edges for other nodes in the graph.
type ChannelLinkEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelLinkEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelLinkEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channellink.FieldPosition:
			values[i] = new(sql.NullInt64)
		case channellink.FieldTitle, channellink.FieldURL:
			values[i] = new(sql.NullString)
		case channellink.FieldCreatedAt, channellink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case channellink.FieldID:
			values[i] = new(uuid.UUID)
		case channellink.ForeignKeys[0]: // channel_link_channel
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case channellink.ForeignKeys[1]: // channel_link_created_by
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelLink fields.
func (_m *ChannelLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channellink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case channellink.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case channellink.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case channellink.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case channellink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channellink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channellink.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field channel_link_channel", values[i])
			} else if value.Valid {
				_m.channel_link_channel = new(uuid.UUID)
				*_m.channel_link_channel = *value.S.(*uuid.UUID)
			}
		case channellink.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field channel_link_created_by", values[i])
			} else if value.Valid {
				_m.channel_link_created_by = new(uuid.UUID)
				*_m.channel_link_created_by = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelLink.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelLink entity.
func (_m *ChannelLink) QueryChannel() *ChannelQuery {
	return NewChannelLinkClient(_m.config).QueryChannel(_m)
}

// QueryCreatedBy queries the "created_by" edge of the ChannelLink entity.
func (_m *ChannelLink) QueryCreatedBy() *UserQuery {
	return NewChannelLinkClient(_m.config).QueryCreatedBy(_m)
}

// Update returns a builder for updating this ChannelLink.
// Note that you need to call ChannelLink.Unwrap() before calling this method if this ChannelLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelLink) Update() *ChannelLinkUpdateOne {
	return NewChannelLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelLink) Unwrap() *ChannelLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelLink) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelLinks is a parsable slice of ChannelLink.
type ChannelLinks []*ChannelLink
