// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/channelcategory"
	"github.com/newt239/chat/ent/channelcategoryitem"
	"github.com/newt239/chat/ent/predicate"
	"github.com/newt239/chat/ent/user"
)

// ChannelCategoryItemUpdate is the builder for updating ChannelCategoryItem entities.
type ChannelCategoryItemUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelCategoryItemMutation
}

// Where appends a list predicates to the ChannelCategoryItemUpdate builder.
func (_u *ChannelCategoryItemUpdate) Where(ps ...predicate.ChannelCategoryItem) *ChannelCategoryItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *ChannelCategoryItemUpdate) SetCategoryID(v uuid.UUID) *ChannelCategoryItemUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdate) SetNillableCategoryID(v *uuid.UUID) *ChannelCategoryItemUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelCategoryItemUpdate) SetUserID(v uuid.UUID) *ChannelCategoryItemUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdate) SetNillableUserID(v *uuid.UUID) *ChannelCategoryItemUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelCategoryItemUpdate) SetChannelID(v uuid.UUID) *ChannelCategoryItemUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdate) SetNillableChannelID(v *uuid.UUID) *ChannelCategoryItemUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetCategory sets the "category" edge to the ChannelCategory entity.
func (_u *ChannelCategoryItemUpdate) SetCategory(v *ChannelCategory) *ChannelCategoryItemUpdate {
	return _u.SetCategoryID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelCategoryItemUpdate) SetUser(v *User) *ChannelCategoryItemUpdate {
	return _u.SetUserID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelCategoryItemUpdate) SetChannel(v *Channel) *ChannelCategoryItemUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ChannelCategoryItemMutation object of the builder.
func (_u *ChannelCategoryItemUpdate) Mutation() *ChannelCategoryItemMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the ChannelCategory entity.
func (_u *ChannelCategoryItemUpdate) ClearCategory() *ChannelCategoryItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelCategoryItemUpdate) ClearUser() *ChannelCategoryItemUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelCategoryItemUpdate) ClearChannel() *ChannelCategoryItemUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelCategoryItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelCategoryItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelCategoryItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelCategoryItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelCategoryItemUpdate) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.category"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.user"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.channel"`)
	}
	return nil
}

func (_u *ChannelCategoryItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelcategoryitem.Table, channelcategoryitem.Columns, sqlgraph.NewFieldSpec(channelcategoryitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcategoryitem.CategoryTable,
			Columns: []string{channelcategoryitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelcategory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcategoryitem.CategoryTable,
			Columns: []string{channelcategoryitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.UserTable,
			Columns: []string{channelcategoryitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.UserTable,
			Columns: []string{channelcategoryitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.ChannelTable,
			Columns: []string{channelcategoryitem.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.ChannelTable,
			Columns: []string{channelcategoryitem.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelcategoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelCategoryItemUpdateOne is the builder for updating a single ChannelCategoryItem entity.
type ChannelCategoryItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelCategoryItemMutation
}

// SetCategoryID sets the "category_id" field.
func (_u *ChannelCategoryItemUpdateOne) SetCategoryID(v uuid.UUID) *ChannelCategoryItemUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdateOne) SetNillableCategoryID(v *uuid.UUID) *ChannelCategoryItemUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelCategoryItemUpdateOne) SetUserID(v uuid.UUID) *ChannelCategoryItemUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdateOne) SetNillableUserID(v *uuid.UUID) *ChannelCategoryItemUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelCategoryItemUpdateOne) SetChannelID(v uuid.UUID) *ChannelCategoryItemUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelCategoryItemUpdateOne) SetNillableChannelID(v *uuid.UUID) *ChannelCategoryItemUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetCategory sets the "category" edge to the ChannelCategory entity.
func (_u *ChannelCategoryItemUpdateOne) SetCategory(v *ChannelCategory) *ChannelCategoryItemUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelCategoryItemUpdateOne) SetUser(v *User) *ChannelCategoryItemUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelCategoryItemUpdateOne) SetChannel(v *Channel) *ChannelCategoryItemUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the ChannelCategoryItemMutation object of the builder.
func (_u *ChannelCategoryItemUpdateOne) Mutation() *ChannelCategoryItemMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the ChannelCategory entity.
func (_u *ChannelCategoryItemUpdateOne) ClearCategory() *ChannelCategoryItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelCategoryItemUpdateOne) ClearUser() *ChannelCategoryItemUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelCategoryItemUpdateOne) ClearChannel() *ChannelCategoryItemUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the ChannelCategoryItemUpdate builder.
func (_u *ChannelCategoryItemUpdateOne) Where(ps ...predicate.ChannelCategoryItem) *ChannelCategoryItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelCategoryItemUpdateOne) Select(field string, fields ...string) *ChannelCategoryItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelCategoryItem entity.
func (_u *ChannelCategoryItemUpdateOne) Save(ctx context.Context) (*ChannelCategoryItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelCategoryItemUpdateOne) SaveX(ctx context.Context) *ChannelCategoryItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelCategoryItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelCategoryItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelCategoryItemUpdateOne) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.category"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.user"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCategoryItem.channel"`)
	}
	return nil
}

func (_u *ChannelCategoryItemUpdateOne) sqlSave(ctx context.Context) (_node *ChannelCategoryItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelcategoryitem.Table, channelcategoryitem.Columns, sqlgraph.NewFieldSpec(channelcategoryitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelCategoryItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelcategoryitem.FieldID)
		for _, f := range fields {
			if !channelcategoryitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelcategoryitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcategoryitem.CategoryTable,
			Columns: []string{channelcategoryitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelcategory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelcategoryitem.CategoryTable,
			Columns: []string{channelcategoryitem.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.UserTable,
			Columns: []string{channelcategoryitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.UserTable,
			Columns: []string{channelcategoryitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.ChannelTable,
			Columns: []string{channelcategoryitem.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelcategoryitem.ChannelTable,
			Columns: []string{channelcategoryitem.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelCategoryItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelcategoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
