// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/newt239/chat/ent/draft"
	"github.com/newt239/chat/ent/predicate"
)

// DraftUpdate is the builder for updating Draft entities.
type DraftUpdate struct {
	config
	hooks    []Hook
	mutation *DraftMutation
}

// Where appends a list predicates to the DraftUpdate builder.
func (_u *DraftUpdate) Where(ps ...predicate.Draft) *DraftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *DraftUpdate) SetBody(v string) *DraftUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DraftUpdate) SetNillableBody(v *string) *DraftUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DraftUpdate) SetUpdatedAt(v time.Time) *DraftUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DraftMutation object of the builder.
func (_u *DraftUpdate) Mutation() *DraftMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DraftUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DraftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DraftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DraftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DraftUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := draft.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DraftUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Draft.user"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Draft.channel"`)
	}
	return nil
}

func (_u *DraftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(draft.Table, draft.Columns, sqlgraph.NewFieldSpec(draft.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(draft.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(draft.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{draft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DraftUpdateOne is the builder for updating a single Draft entity.
type DraftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DraftMutation
}

// SetBody sets the "body" field.
func (_u *DraftUpdateOne) SetBody(v string) *DraftUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *DraftUpdateOne) SetNillableBody(v *string) *DraftUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DraftUpdateOne) SetUpdatedAt(v time.Time) *DraftUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DraftMutation object of the builder.
func (_u *DraftUpdateOne) Mutation() *DraftMutation {
	return _u.mutation
}

// Where appends a list predicates to the DraftUpdate builder.
func (_u *DraftUpdateOne) Where(ps ...predicate.Draft) *DraftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DraftUpdateOne) Select(field string, fields ...string) *DraftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Draft entity.
func (_u *DraftUpdateOne) Save(ctx context.Context) (*Draft, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DraftUpdateOne) SaveX(ctx context.Context) *Draft {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DraftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DraftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DraftUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := draft.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DraftUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Draft.user"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Draft.channel"`)
	}
	return nil
}

func (_u *DraftUpdateOne) sqlSave(ctx context.Context) (_node *Draft, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(draft.Table, draft.Columns, sqlgraph.NewFieldSpec(draft.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Draft.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, draft.FieldID)
		for _, f := range fields {
			if !draft.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != draft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(draft.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(draft.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Draft{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{draft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
