// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/message"
	"github.com/newt239/chat/ent/messagegroupmention"
	"github.com/newt239/chat/ent/usergroup"
)

// MessageGroupMention is the model entity for the MessageGroupMention schema.
type MessageGroupMention struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessageGroupMentionQuery when eager-loading is set.
	Edges                         MessageGroupMentionEdges `json:"edges"`
	message_group_mention_message *uuid.UUID
	message_group_mention_group   *uuid.UUID
	selectValues                  sql.SelectValues
}

// MessageGroupMentionEdges holds the relations/edges for other nodes in the graph.
type MessageGroupMentionEdges struct {
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// Group holds the value of the group edge.
	Group *UserGroup `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageGroupMentionEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageGroupMentionEdges) GroupOrErr() (*UserGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usergroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageGroupMention) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messagegroupmention.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case messagegroupmention.FieldID:
			values[i] = new(uuid.UUID)
		case messagegroupmention.ForeignKeys[0]: // message_group_mention_message
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case messagegroupmention.ForeignKeys[1]: // message_group_mention_group
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageGroupMention fields.
func (_m *MessageGroupMention) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messagegroupmention.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case messagegroupmention.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case messagegroupmention.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_group_mention_message", values[i])
			} else if value.Valid {
				_m.message_group_mention_message = new(uuid.UUID)
				*_m.message_group_mention_message = *value.S.(*uuid.UUID)
			}
		case messagegroupmention.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_group_mention_group", values[i])
			} else if value.Valid {
				_m.message_group_mention_group = new(uuid.UUID)
				*_m.message_group_mention_group = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageGroupMention.
// This includes values selected through modifiers, order, etc.
func (_m *MessageGroupMention) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the MessageGroupMention entity.
func (_m *MessageGroupMention) QueryMessage() *MessageQuery {
	return NewMessageGroupMentionClient(_m.config).QueryMessage(_m)
}

// QueryGroup queries the "group" edge of the MessageGroupMention entity.
func (_m *MessageGroupMention) QueryGroup() *UserGroupQuery {
	return NewMessageGroupMentionClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this MessageGroupMention.
// Note that you need to call MessageGroupMention.Unwrap() before calling this method if this MessageGroupMention
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MessageGroupMention) Update() *MessageGroupMentionUpdateOne {
	return NewMessageGroupMentionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MessageGroupMention entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MessageGroupMention) Unwrap() *MessageGroupMention {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageGroupMention is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MessageGroupMention) String() string {
	var builder strings.Builder
	builder.WriteString("MessageGroupMention(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MessageGroupMentions is a parsable slice of MessageGroupMention.
type MessageGroupMentions []*MessageGroupMention
