// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/attachment"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/message"
	"github.com/newt239/chat/ent/messagebookmark"
	"github.com/newt239/chat/ent/messagegroupmention"
	"github.com/newt239/chat/ent/messagelink"
	"github.com/newt239/chat/ent/messagereaction"
	"github.com/newt239/chat/ent/messageusermention"
	"github.com/newt239/chat/ent/predicate"
	"github.com/newt239/chat/ent/threadmetadata"
	"github.com/newt239/chat/ent/threadreadstate"
	"github.com/newt239/chat/ent/user"
	"github.com/newt239/chat/ent/userthreadfollow"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *MessageUpdate) SetBody(v string) *MessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableBody(v *string) *MessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *MessageUpdate) SetEditedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableEditedAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *MessageUpdate) ClearEditedAt() *MessageUpdate {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MessageUpdate) SetDeletedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableDeletedAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MessageUpdate) ClearDeletedAt() *MessageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *MessageUpdate) SetDeletedBy(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableDeletedBy(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *MessageUpdate) ClearDeletedBy() *MessageUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *MessageUpdate) SetChannelID(id uuid.UUID) *MessageUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *MessageUpdate) SetChannel(v *Channel) *MessageUpdate {
	return _u.SetChannelID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *MessageUpdate) SetUserID(id uuid.UUID) *MessageUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MessageUpdate) SetUser(v *User) *MessageUpdate {
	return _u.SetUserID(v.ID)
}

// SetParentID sets the "parent" edge to the Message entity by ID.
func (_u *MessageUpdate) SetParentID(id uuid.UUID) *MessageUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Message entity by ID if the given value is not nil.
func (_u *MessageUpdate) SetNillableParentID(id *uuid.UUID) *MessageUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Message entity.
func (_u *MessageUpdate) SetParent(v *Message) *MessageUpdate {
	return _u.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the Message entity by IDs.
func (_u *MessageUpdate) AddReplyIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the Message entity.
func (_u *MessageUpdate) AddReplies(v ...*Message) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// AddReactionIDs adds the "reactions" edge to the MessageReaction entity by IDs.
func (_u *MessageUpdate) AddReactionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddReactionIDs(ids...)
	return _u
}

// AddReactions adds the "reactions" edges to the MessageReaction entity.
func (_u *MessageUpdate) AddReactions(v ...*MessageReaction) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReactionIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the MessageBookmark entity by IDs.
func (_u *MessageUpdate) AddBookmarkIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the MessageBookmark entity.
func (_u *MessageUpdate) AddBookmarks(v ...*MessageBookmark) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// AddUserMentionIDs adds the "user_mentions" edge to the MessageUserMention entity by IDs.
func (_u *MessageUpdate) AddUserMentionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddUserMentionIDs(ids...)
	return _u
}

// AddUserMentions adds the "user_mentions" edges to the MessageUserMention entity.
func (_u *MessageUpdate) AddUserMentions(v ...*MessageUserMention) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserMentionIDs(ids...)
}

// AddGroupMentionIDs adds the "group_mentions" edge to the MessageGroupMention entity by IDs.
func (_u *MessageUpdate) AddGroupMentionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddGroupMentionIDs(ids...)
	return _u
}

// AddGroupMentions adds the "group_mentions" edges to the MessageGroupMention entity.
func (_u *MessageUpdate) AddGroupMentions(v ...*MessageGroupMention) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupMentionIDs(ids...)
}

// AddLinkIDs adds the "links" edge to the MessageLink entity by IDs.
func (_u *MessageUpdate) AddLinkIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the MessageLink entity.
func (_u *MessageUpdate) AddLinks(v ...*MessageLink) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *MessageUpdate) AddAttachmentIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *MessageUpdate) AddAttachments(v ...*Attachment) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddThreadMetadatumIDs adds the "thread_metadata" edge to the ThreadMetadata entity by IDs.
func (_u *MessageUpdate) AddThreadMetadatumIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddThreadMetadatumIDs(ids...)
	return _u
}

// AddThreadMetadata adds the "thread_metadata" edges to the ThreadMetadata entity.
func (_u *MessageUpdate) AddThreadMetadata(v ...*ThreadMetadata) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadMetadatumIDs(ids...)
}

// AddUserThreadFollowIDs adds the "user_thread_follows" edge to the UserThreadFollow entity by IDs.
func (_u *MessageUpdate) AddUserThreadFollowIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddUserThreadFollowIDs(ids...)
	return _u
}

// AddUserThreadFollows adds the "user_thread_follows" edges to the UserThreadFollow entity.
func (_u *MessageUpdate) AddUserThreadFollows(v ...*UserThreadFollow) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserThreadFollowIDs(ids...)
}

// AddThreadReadStateIDs adds the "thread_read_states" edge to the ThreadReadState entity by IDs.
func (_u *MessageUpdate) AddThreadReadStateIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddThreadReadStateIDs(ids...)
	return _u
}

// AddThreadReadStates adds the "thread_read_states" edges to the ThreadReadState entity.
func (_u *MessageUpdate) AddThreadReadStates(v ...*ThreadReadState) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadReadStateIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *MessageUpdate) ClearChannel() *MessageUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MessageUpdate) ClearUser() *MessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the Message entity.
func (_u *MessageUpdate) ClearParent() *MessageUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearReplies clears all "replies" edges to the Message entity.
func (_u *MessageUpdate) ClearReplies() *MessageUpdate {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to Message entities by IDs.
func (_u *MessageUpdate) RemoveReplyIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to Message entities.
func (_u *MessageUpdate) RemoveReplies(v ...*Message) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearReactions clears all "reactions" edges to the MessageReaction entity.
func (_u *MessageUpdate) ClearReactions() *MessageUpdate {
	_u.mutation.ClearReactions()
	return _u
}

// RemoveReactionIDs removes the "reactions" edge to MessageReaction entities by IDs.
func (_u *MessageUpdate) RemoveReactionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveReactionIDs(ids...)
	return _u
}

// RemoveReactions removes "reactions" edges to MessageReaction entities.
func (_u *MessageUpdate) RemoveReactions(v ...*MessageReaction) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReactionIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the MessageBookmark entity.
func (_u *MessageUpdate) ClearBookmarks() *MessageUpdate {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to MessageBookmark entities by IDs.
func (_u *MessageUpdate) RemoveBookmarkIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to MessageBookmark entities.
func (_u *MessageUpdate) RemoveBookmarks(v ...*MessageBookmark) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// ClearUserMentions clears all "user_mentions" edges to the MessageUserMention entity.
func (_u *MessageUpdate) ClearUserMentions() *MessageUpdate {
	_u.mutation.ClearUserMentions()
	return _u
}

// RemoveUserMentionIDs removes the "user_mentions" edge to MessageUserMention entities by IDs.
func (_u *MessageUpdate) RemoveUserMentionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveUserMentionIDs(ids...)
	return _u
}

// RemoveUserMentions removes "user_mentions" edges to MessageUserMention entities.
func (_u *MessageUpdate) RemoveUserMentions(v ...*MessageUserMention) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserMentionIDs(ids...)
}

// ClearGroupMentions clears all "group_mentions" edges to the MessageGroupMention entity.
func (_u *MessageUpdate) ClearGroupMentions() *MessageUpdate {
	_u.mutation.ClearGroupMentions()
	return _u
}

// RemoveGroupMentionIDs removes the "group_mentions" edge to MessageGroupMention entities by IDs.
func (_u *MessageUpdate) RemoveGroupMentionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveGroupMentionIDs(ids...)
	return _u
}

// RemoveGroupMentions removes "group_mentions" edges to MessageGroupMention entities.
func (_u *MessageUpdate) RemoveGroupMentions(v ...*MessageGroupMention) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupMentionIDs(ids...)
}

// ClearLinks clears all "links" edges to the MessageLink entity.
func (_u *MessageUpdate) ClearLinks() *MessageUpdate {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to MessageLink entities by IDs.
func (_u *MessageUpdate) RemoveLinkIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to MessageLink entities.
func (_u *MessageUpdate) RemoveLinks(v ...*MessageLink) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *MessageUpdate) ClearAttachments() *MessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *MessageUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *MessageUpdate) RemoveAttachments(v ...*Attachment) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearThreadMetadata clears all "thread_metadata" edges to the ThreadMetadata entity.
func (_u *MessageUpdate) ClearThreadMetadata() *MessageUpdate {
	_u.mutation.ClearThreadMetadata()
	return _u
}

// RemoveThreadMetadatumIDs removes the "thread_metadata" edge to ThreadMetadata entities by IDs.
func (_u *MessageUpdate) RemoveThreadMetadatumIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveThreadMetadatumIDs(ids...)
	return _u
}

// RemoveThreadMetadata removes "thread_metadata" edges to ThreadMetadata entities.
func (_u *MessageUpdate) RemoveThreadMetadata(v ...*ThreadMetadata) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadMetadatumIDs(ids...)
}

// ClearUserThreadFollows clears all "user_thread_follows" edges to the UserThreadFollow entity.
func (_u *MessageUpdate) ClearUserThreadFollows() *MessageUpdate {
	_u.mutation.ClearUserThreadFollows()
	return _u
}

// RemoveUserThreadFollowIDs removes the "user_thread_follows" edge to UserThreadFollow entities by IDs.
func (_u *MessageUpdate) RemoveUserThreadFollowIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveUserThreadFollowIDs(ids...)
	return _u
}

// RemoveUserThreadFollows removes "user_thread_follows" edges to UserThreadFollow entities.
func (_u *MessageUpdate) RemoveUserThreadFollows(v ...*UserThreadFollow) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserThreadFollowIDs(ids...)
}

// ClearThreadReadStates clears all "thread_read_states" edges to the ThreadReadState entity.
func (_u *MessageUpdate) ClearThreadReadStates() *MessageUpdate {
	_u.mutation.ClearThreadReadStates()
	return _u
}

// RemoveThreadReadStateIDs removes the "thread_read_states" edge to ThreadReadState entities by IDs.
func (_u *MessageUpdate) RemoveThreadReadStateIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveThreadReadStateIDs(ids...)
	return _u
}

// RemoveThreadReadStates removes "thread_read_states" edges to ThreadReadState entities.
func (_u *MessageUpdate) RemoveThreadReadStates(v ...*ThreadReadState) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadReadStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := message.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Message.body": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.user"`)
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(message.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(message.FieldEditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(message.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(message.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(message.FieldDeletedBy, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(message.FieldDeletedBy, field.TypeUUID)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ParentTable,
			Columns: []string{message.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ParentTable,
			Columns: []string{message.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReactionsIDs(); len(nodes) > 0 && !_u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserMentionsIDs(); len(nodes) > 0 && !_u.mutation.UserMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupMentionsIDs(); len(nodes) > 0 && !_u.mutation.GroupMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadMetadataIDs(); len(nodes) > 0 && !_u.mutation.ThreadMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserThreadFollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserThreadFollowsIDs(); len(nodes) > 0 && !_u.mutation.UserThreadFollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserThreadFollowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadReadStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadReadStatesIDs(); len(nodes) > 0 && !_u.mutation.ThreadReadStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadReadStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetBody sets the "body" field.
func (_u *MessageUpdateOne) SetBody(v string) *MessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableBody(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *MessageUpdateOne) SetEditedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableEditedAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *MessageUpdateOne) ClearEditedAt() *MessageUpdateOne {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MessageUpdateOne) SetDeletedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableDeletedAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MessageUpdateOne) ClearDeletedAt() *MessageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *MessageUpdateOne) SetDeletedBy(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableDeletedBy(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *MessageUpdateOne) ClearDeletedBy() *MessageUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *MessageUpdateOne) SetChannelID(id uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *MessageUpdateOne) SetChannel(v *Channel) *MessageUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *MessageUpdateOne) SetUserID(id uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MessageUpdateOne) SetUser(v *User) *MessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetParentID sets the "parent" edge to the Message entity by ID.
func (_u *MessageUpdateOne) SetParentID(id uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Message entity by ID if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableParentID(id *uuid.UUID) *MessageUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Message entity.
func (_u *MessageUpdateOne) SetParent(v *Message) *MessageUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the Message entity by IDs.
func (_u *MessageUpdateOne) AddReplyIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the Message entity.
func (_u *MessageUpdateOne) AddReplies(v ...*Message) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// AddReactionIDs adds the "reactions" edge to the MessageReaction entity by IDs.
func (_u *MessageUpdateOne) AddReactionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddReactionIDs(ids...)
	return _u
}

// AddReactions adds the "reactions" edges to the MessageReaction entity.
func (_u *MessageUpdateOne) AddReactions(v ...*MessageReaction) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReactionIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the MessageBookmark entity by IDs.
func (_u *MessageUpdateOne) AddBookmarkIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the MessageBookmark entity.
func (_u *MessageUpdateOne) AddBookmarks(v ...*MessageBookmark) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// AddUserMentionIDs adds the "user_mentions" edge to the MessageUserMention entity by IDs.
func (_u *MessageUpdateOne) AddUserMentionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddUserMentionIDs(ids...)
	return _u
}

// AddUserMentions adds the "user_mentions" edges to the MessageUserMention entity.
func (_u *MessageUpdateOne) AddUserMentions(v ...*MessageUserMention) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserMentionIDs(ids...)
}

// AddGroupMentionIDs adds the "group_mentions" edge to the MessageGroupMention entity by IDs.
func (_u *MessageUpdateOne) AddGroupMentionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddGroupMentionIDs(ids...)
	return _u
}

// AddGroupMentions adds the "group_mentions" edges to the MessageGroupMention entity.
func (_u *MessageUpdateOne) AddGroupMentions(v ...*MessageGroupMention) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupMentionIDs(ids...)
}

// AddLinkIDs adds the "links" edge to the MessageLink entity by IDs.
func (_u *MessageUpdateOne) AddLinkIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the MessageLink entity.
func (_u *MessageUpdateOne) AddLinks(v ...*MessageLink) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *MessageUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *MessageUpdateOne) AddAttachments(v ...*Attachment) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddThreadMetadatumIDs adds the "thread_metadata" edge to the ThreadMetadata entity by IDs.
func (_u *MessageUpdateOne) AddThreadMetadatumIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddThreadMetadatumIDs(ids...)
	return _u
}

// AddThreadMetadata adds the "thread_metadata" edges to the ThreadMetadata entity.
func (_u *MessageUpdateOne) AddThreadMetadata(v ...*ThreadMetadata) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadMetadatumIDs(ids...)
}

// AddUserThreadFollowIDs adds the "user_thread_follows" edge to the UserThreadFollow entity by IDs.
func (_u *MessageUpdateOne) AddUserThreadFollowIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddUserThreadFollowIDs(ids...)
	return _u
}

// AddUserThreadFollows adds the "user_thread_follows" edges to the UserThreadFollow entity.
func (_u *MessageUpdateOne) AddUserThreadFollows(v ...*UserThreadFollow) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserThreadFollowIDs(ids...)
}

// AddThreadReadStateIDs adds the "thread_read_states" edge to the ThreadReadState entity by IDs.
func (_u *MessageUpdateOne) AddThreadReadStateIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddThreadReadStateIDs(ids...)
	return _u
}

// AddThreadReadStates adds the "thread_read_states" edges to the ThreadReadState entity.
func (_u *MessageUpdateOne) AddThreadReadStates(v ...*ThreadReadState) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadReadStateIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *MessageUpdateOne) ClearChannel() *MessageUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MessageUpdateOne) ClearUser() *MessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the Message entity.
func (_u *MessageUpdateOne) ClearParent() *MessageUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearReplies clears all "replies" edges to the Message entity.
func (_u *MessageUpdateOne) ClearReplies() *MessageUpdateOne {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to Message entities by IDs.
func (_u *MessageUpdateOne) RemoveReplyIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to Message entities.
func (_u *MessageUpdateOne) RemoveReplies(v ...*Message) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearReactions clears all "reactions" edges to the MessageReaction entity.
func (_u *MessageUpdateOne) ClearReactions() *MessageUpdateOne {
	_u.mutation.ClearReactions()
	return _u
}

// RemoveReactionIDs removes the "reactions" edge to MessageReaction entities by IDs.
func (_u *MessageUpdateOne) RemoveReactionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveReactionIDs(ids...)
	return _u
}

// RemoveReactions removes "reactions" edges to MessageReaction entities.
func (_u *MessageUpdateOne) RemoveReactions(v ...*MessageReaction) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReactionIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the MessageBookmark entity.
func (_u *MessageUpdateOne) ClearBookmarks() *MessageUpdateOne {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to MessageBookmark entities by IDs.
func (_u *MessageUpdateOne) RemoveBookmarkIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to MessageBookmark entities.
func (_u *MessageUpdateOne) RemoveBookmarks(v ...*MessageBookmark) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// ClearUserMentions clears all "user_mentions" edges to the MessageUserMention entity.
func (_u *MessageUpdateOne) ClearUserMentions() *MessageUpdateOne {
	_u.mutation.ClearUserMentions()
	return _u
}

// RemoveUserMentionIDs removes the "user_mentions" edge to MessageUserMention entities by IDs.
func (_u *MessageUpdateOne) RemoveUserMentionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveUserMentionIDs(ids...)
	return _u
}

// RemoveUserMentions removes "user_mentions" edges to MessageUserMention entities.
func (_u *MessageUpdateOne) RemoveUserMentions(v ...*MessageUserMention) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserMentionIDs(ids...)
}

// ClearGroupMentions clears all "group_mentions" edges to the MessageGroupMention entity.
func (_u *MessageUpdateOne) ClearGroupMentions() *MessageUpdateOne {
	_u.mutation.ClearGroupMentions()
	return _u
}

// RemoveGroupMentionIDs removes the "group_mentions" edge to MessageGroupMention entities by IDs.
func (_u *MessageUpdateOne) RemoveGroupMentionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveGroupMentionIDs(ids...)
	return _u
}

// RemoveGroupMentions removes "group_mentions" edges to MessageGroupMention entities.
func (_u *MessageUpdateOne) RemoveGroupMentions(v ...*MessageGroupMention) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupMentionIDs(ids...)
}

// ClearLinks clears all "links" edges to the MessageLink entity.
func (_u *MessageUpdateOne) ClearLinks() *MessageUpdateOne {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to MessageLink entities by IDs.
func (_u *MessageUpdateOne) RemoveLinkIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to MessageLink entities.
func (_u *MessageUpdateOne) RemoveLinks(v ...*MessageLink) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *MessageUpdateOne) ClearAttachments() *MessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *MessageUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *MessageUpdateOne) RemoveAttachments(v ...*Attachment) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearThreadMetadata clears all "thread_metadata" edges to the ThreadMetadata entity.
func (_u *MessageUpdateOne) ClearThreadMetadata() *MessageUpdateOne {
	_u.mutation.ClearThreadMetadata()
	return _u
}

// RemoveThreadMetadatumIDs removes the "thread_metadata" edge to ThreadMetadata entities by IDs.
func (_u *MessageUpdateOne) RemoveThreadMetadatumIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveThreadMetadatumIDs(ids...)
	return _u
}

// RemoveThreadMetadata removes "thread_metadata" edges to ThreadMetadata entities.
func (_u *MessageUpdateOne) RemoveThreadMetadata(v ...*ThreadMetadata) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadMetadatumIDs(ids...)
}

// ClearUserThreadFollows clears all "user_thread_follows" edges to the UserThreadFollow entity.
func (_u *MessageUpdateOne) ClearUserThreadFollows() *MessageUpdateOne {
	_u.mutation.ClearUserThreadFollows()
	return _u
}

// RemoveUserThreadFollowIDs removes the "user_thread_follows" edge to UserThreadFollow entities by IDs.
func (_u *MessageUpdateOne) RemoveUserThreadFollowIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveUserThreadFollowIDs(ids...)
	return _u
}

// RemoveUserThreadFollows removes "user_thread_follows" edges to UserThreadFollow entities.
func (_u *MessageUpdateOne) RemoveUserThreadFollows(v ...*UserThreadFollow) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserThreadFollowIDs(ids...)
}

// ClearThreadReadStates clears all "thread_read_states" edges to the ThreadReadState entity.
func (_u *MessageUpdateOne) ClearThreadReadStates() *MessageUpdateOne {
	_u.mutation.ClearThreadReadStates()
	return _u
}

// RemoveThreadReadStateIDs removes the "thread_read_states" edge to ThreadReadState entities by IDs.
func (_u *MessageUpdateOne) RemoveThreadReadStateIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveThreadReadStateIDs(ids...)
	return _u
}

// RemoveThreadReadStates removes "thread_read_states" edges to ThreadReadState entities.
func (_u *MessageUpdateOne) RemoveThreadReadStates(v ...*ThreadReadState) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadReadStateIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := message.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Message.body": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.user"`)
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(message.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(message.FieldEditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(message.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(message.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(message.FieldDeletedBy, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(message.FieldDeletedBy, field.TypeUUID)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ParentTable,
			Columns: []string{message.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ParentTable,
			Columns: []string{message.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReactionsIDs(); len(nodes) > 0 && !_u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagereaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.BookmarksTable,
			Columns: []string{message.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagebookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserMentionsIDs(); len(nodes) > 0 && !_u.mutation.UserMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserMentionsTable,
			Columns: []string{message.UserMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messageusermention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupMentionsIDs(); len(nodes) > 0 && !_u.mutation.GroupMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.GroupMentionsTable,
			Columns: []string{message.GroupMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagegroupmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.LinksTable,
			Columns: []string{message.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadMetadataIDs(); len(nodes) > 0 && !_u.mutation.ThreadMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadMetadataTable,
			Columns: []string{message.ThreadMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadmetadata.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserThreadFollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserThreadFollowsIDs(); len(nodes) > 0 && !_u.mutation.UserThreadFollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserThreadFollowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.UserThreadFollowsTable,
			Columns: []string{message.UserThreadFollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userthreadfollow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadReadStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadReadStatesIDs(); len(nodes) > 0 && !_u.mutation.ThreadReadStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadReadStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.ThreadReadStatesTable,
			Columns: []string{message.ThreadReadStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadreadstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
