// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/message"
	"github.com/newt239/chat/ent/messagelink"
)

// MessageLinkCreate is the builder for creating a MessageLink entity.
type MessageLinkCreate struct {
	config
	mutation *MessageLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetURL sets the "url" field.
func (_c *MessageLinkCreate) SetURL(v string) *MessageLinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MessageLinkCreate) SetTitle(v string) *MessageLinkCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableTitle(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MessageLinkCreate) SetDescription(v string) *MessageLinkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableDescription(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *MessageLinkCreate) SetImageURL(v string) *MessageLinkCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableImageURL(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetSiteName sets the "site_name" field.
func (_c *MessageLinkCreate) SetSiteName(v string) *MessageLinkCreate {
	_c.mutation.SetSiteName(v)
	return _c
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableSiteName(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetSiteName(*v)
	}
	return _c
}

// SetCardType sets the "card_type" field.
func (_c *MessageLinkCreate) SetCardType(v string) *MessageLinkCreate {
	_c.mutation.SetCardType(v)
	return _c
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableCardType(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetCardType(*v)
	}
	return _c
}

// SetImageWidth sets the "image_width" field.
func (_c *MessageLinkCreate) SetImageWidth(v int32) *MessageLinkCreate {
	_c.mutation.SetImageWidth(v)
	return _c
}

// SetNillableImageWidth sets the "image_width" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableImageWidth(v *int32) *MessageLinkCreate {
	if v != nil {
		_c.SetImageWidth(*v)
	}
	return _c
}

// SetImageHeight sets the "image_height" field.
func (_c *MessageLinkCreate) SetImageHeight(v int32) *MessageLinkCreate {
	_c.mutation.SetImageHeight(v)
	return _c
}

// SetNillableImageHeight sets the "image_height" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableImageHeight(v *int32) *MessageLinkCreate {
	if v != nil {
		_c.SetImageHeight(*v)
	}
	return _c
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (_c *MessageLinkCreate) SetYoutubeVideoID(v string) *MessageLinkCreate {
	_c.mutation.SetYoutubeVideoID(v)
	return _c
}

// SetNillableYoutubeVideoID sets the "youtube_video_id" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableYoutubeVideoID(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetYoutubeVideoID(*v)
	}
	return _c
}

// SetYoutubeChannelName sets the "youtube_channel_name" field.
func (_c *MessageLinkCreate) SetYoutubeChannelName(v string) *MessageLinkCreate {
	_c.mutation.SetYoutubeChannelName(v)
	return _c
}

// SetNillableYoutubeChannelName sets the "youtube_channel_name" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableYoutubeChannelName(v *string) *MessageLinkCreate {
	if v != nil {
		_c.SetYoutubeChannelName(*v)
	}
	return _c
}

// SetYoutubeDurationSeconds sets the "youtube_duration_seconds" field.
func (_c *MessageLinkCreate) SetYoutubeDurationSeconds(v int32) *MessageLinkCreate {
	_c.mutation.SetYoutubeDurationSeconds(v)
	return _c
}

// SetNillableYoutubeDurationSeconds sets the "youtube_duration_seconds" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableYoutubeDurationSeconds(v *int32) *MessageLinkCreate {
	if v != nil {
		_c.SetYoutubeDurationSeconds(*v)
	}
	return _c
}

// SetLinkedMessageID sets the "linked_message_id" field.
func (_c *MessageLinkCreate) SetLinkedMessageID(v uuid.UUID) *MessageLinkCreate {
	_c.mutation.SetLinkedMessageID(v)
	return _c
}

// SetNillableLinkedMessageID sets the "linked_message_id" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableLinkedMessageID(v *uuid.UUID) *MessageLinkCreate {
	if v != nil {
		_c.SetLinkedMessageID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessageLinkCreate) SetCreatedAt(v time.Time) *MessageLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableCreatedAt(v *time.Time) *MessageLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MessageLinkCreate) SetID(v uuid.UUID) *MessageLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MessageLinkCreate) SetNillableID(v *uuid.UUID) *MessageLinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_c *MessageLinkCreate) SetMessageID(id uuid.UUID) *MessageLinkCreate {
	_c.mutation.SetMessageID(id)
	return _c
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *MessageLinkCreate) SetMessage(v *Message) *MessageLinkCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the MessageLinkMutation object of the builder.
func (_c *MessageLinkCreate) Mutation() *MessageLinkMutation {
	return _c.mutation
}

// Save creates the MessageLink in the database.
func (_c *MessageLinkCreate) Save(ctx context.Context) (*MessageLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageLinkCreate) SaveX(ctx context.Context) *MessageLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageLinkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := messagelink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := messagelink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageLinkCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "MessageLink.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := messagelink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MessageLink.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MessageLink.created_at"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "MessageLink.message"`)}
	}
	return nil
}

func (_c *MessageLinkCreate) sqlSave(ctx context.Context) (*MessageLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageLinkCreate) createSpec() (*MessageLink, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(messagelink.Table, sqlgraph.NewFieldSpec(messagelink.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(messagelink.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(messagelink.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(messagelink.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(messagelink.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.SiteName(); ok {
		_spec.SetField(messagelink.FieldSiteName, field.TypeString, value)
		_node.SiteName = value
	}
	if value, ok := _c.mutation.CardType(); ok {
		_spec.SetField(messagelink.FieldCardType, field.TypeString, value)
		_node.CardType = value
	}
	if value, ok := _c.mutation.ImageWidth(); ok {
		_spec.SetField(messagelink.FieldImageWidth, field.TypeInt32, value)
		_node.ImageWidth = &value
	}
	if value, ok := _c.mutation.ImageHeight(); ok {
		_spec.SetField(messagelink.FieldImageHeight, field.TypeInt32, value)
		_node.ImageHeight = &value
	}
	if value, ok := _c.mutation.YoutubeVideoID(); ok {
		_spec.SetField(messagelink.FieldYoutubeVideoID, field.TypeString, value)
		_node.YoutubeVideoID = &value
	}
	if value, ok := _c.mutation.YoutubeChannelName(); ok {
		_spec.SetField(messagelink.FieldYoutubeChannelName, field.TypeString, value)
		_node.YoutubeChannelName = &value
	}
	if value, ok := _c.mutation.YoutubeDurationSeconds(); ok {
		_spec.SetField(messagelink.FieldYoutubeDurationSeconds, field.TypeInt32, value)
		_node.YoutubeDurationSeconds = &value
	}
	if value, ok := _c.mutation.LinkedMessageID(); ok {
		_spec.SetField(messagelink.FieldLinkedMessageID, field.TypeUUID, value)
		_node.LinkedMessageID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(messagelink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   messagelink.MessageTable,
			Columns: []string{messagelink.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.message_link_message = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageLink.Create().
//		SetURL(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageLinkUpsert) {
//			SetURL(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageLinkCreate) OnConflict(opts ...sql.ConflictOption) *MessageLinkUpsertOne {
	_c.conflict = opts
	return &MessageLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageLinkCreate) OnConflictColumns(columns ...string) *MessageLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageLinkUpsertOne{
		create: _c,
	}
}

type (
	// MessageLinkUpsertOne is the builder for "upsert"-ing
	//  one MessageLink node.
	MessageLinkUpsertOne struct {
		create *MessageLinkCreate
	}

	// MessageLinkUpsert is the "OnConflict" setter.
	MessageLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetURL sets the "url" field.
func (u *MessageLinkUpsert) SetURL(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateURL() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldURL)
	return u
}

// SetTitle sets the "title" field.
func (u *MessageLinkUpsert) SetTitle(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateTitle() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *MessageLinkUpsert) ClearTitle() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *MessageLinkUpsert) SetDescription(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateDescription() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *MessageLinkUpsert) ClearDescription() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldDescription)
	return u
}

// SetImageURL sets the "image_url" field.
func (u *MessageLinkUpsert) SetImageURL(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldImageURL, v)
	return u
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateImageURL() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldImageURL)
	return u
}

// ClearImageURL clears the value of the "image_url" field.
func (u *MessageLinkUpsert) ClearImageURL() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldImageURL)
	return u
}

// SetSiteName sets the "site_name" field.
func (u *MessageLinkUpsert) SetSiteName(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldSiteName, v)
	return u
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateSiteName() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldSiteName)
	return u
}

// ClearSiteName clears the value of the "site_name" field.
func (u *MessageLinkUpsert) ClearSiteName() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldSiteName)
	return u
}

// SetCardType sets the "card_type" field.
func (u *MessageLinkUpsert) SetCardType(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldCardType, v)
	return u
}

// UpdateCardType sets the "card_type" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateCardType() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldCardType)
	return u
}

// ClearCardType clears the value of the "card_type" field.
func (u *MessageLinkUpsert) ClearCardType() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldCardType)
	return u
}

// SetImageWidth sets the "image_width" field.
func (u *MessageLinkUpsert) SetImageWidth(v int32) *MessageLinkUpsert {
	u.Set(messagelink.FieldImageWidth, v)
	return u
}

// UpdateImageWidth sets the "image_width" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateImageWidth() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldImageWidth)
	return u
}

// AddImageWidth adds v to the "image_width" field.
func (u *MessageLinkUpsert) AddImageWidth(v int32) *MessageLinkUpsert {
	u.Add(messagelink.FieldImageWidth, v)
	return u
}

// ClearImageWidth clears the value of the "image_width" field.
func (u *MessageLinkUpsert) ClearImageWidth() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldImageWidth)
	return u
}

// SetImageHeight sets the "image_height" field.
func (u *MessageLinkUpsert) SetImageHeight(v int32) *MessageLinkUpsert {
	u.Set(messagelink.FieldImageHeight, v)
	return u
}

// UpdateImageHeight sets the "image_height" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateImageHeight() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldImageHeight)
	return u
}

// AddImageHeight adds v to the "image_height" field.
func (u *MessageLinkUpsert) AddImageHeight(v int32) *MessageLinkUpsert {
	u.Add(messagelink.FieldImageHeight, v)
	return u
}

// ClearImageHeight clears the value of the "image_height" field.
func (u *MessageLinkUpsert) ClearImageHeight() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldImageHeight)
	return u
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (u *MessageLinkUpsert) SetYoutubeVideoID(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldYoutubeVideoID, v)
	return u
}

// UpdateYoutubeVideoID sets the "youtube_video_id" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateYoutubeVideoID() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldYoutubeVideoID)
	return u
}

// ClearYoutubeVideoID clears the value of the "youtube_video_id" field.
func (u *MessageLinkUpsert) ClearYoutubeVideoID() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldYoutubeVideoID)
	return u
}

// SetYoutubeChannelName sets the "youtube_channel_name" field.
func (u *MessageLinkUpsert) SetYoutubeChannelName(v string) *MessageLinkUpsert {
	u.Set(messagelink.FieldYoutubeChannelName, v)
	return u
}

// UpdateYoutubeChannelName sets the "youtube_channel_name" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateYoutubeChannelName() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldYoutubeChannelName)
	return u
}

// ClearYoutubeChannelName clears the value of the "youtube_channel_name" field.
func (u *MessageLinkUpsert) ClearYoutubeChannelName() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldYoutubeChannelName)
	return u
}

// SetYoutubeDurationSeconds sets the "youtube_duration_seconds" field.
func (u *MessageLinkUpsert) SetYoutubeDurationSeconds(v int32) *MessageLinkUpsert {
	u.Set(messagelink.FieldYoutubeDurationSeconds, v)
	return u
}

// UpdateYoutubeDurationSeconds sets the "youtube_duration_seconds" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateYoutubeDurationSeconds() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldYoutubeDurationSeconds)
	return u
}

// AddYoutubeDurationSeconds adds v to the "youtube_duration_seconds" field.
func (u *MessageLinkUpsert) AddYoutubeDurationSeconds(v int32) *MessageLinkUpsert {
	u.Add(messagelink.FieldYoutubeDurationSeconds, v)
	return u
}

// ClearYoutubeDurationSeconds clears the value of the "youtube_duration_seconds" field.
func (u *MessageLinkUpsert) ClearYoutubeDurationSeconds() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldYoutubeDurationSeconds)
	return u
}

// SetLinkedMessageID sets the "linked_message_id" field.
func (u *MessageLinkUpsert) SetLinkedMessageID(v uuid.UUID) *MessageLinkUpsert {
	u.Set(messagelink.FieldLinkedMessageID, v)
	return u
}

// UpdateLinkedMessageID sets the "linked_message_id" field to the value that was provided on create.
func (u *MessageLinkUpsert) UpdateLinkedMessageID() *MessageLinkUpsert {
	u.SetExcluded(messagelink.FieldLinkedMessageID)
	return u
}

// ClearLinkedMessageID clears the value of the "linked_message_id" field.
func (u *MessageLinkUpsert) ClearLinkedMessageID() *MessageLinkUpsert {
	u.SetNull(messagelink.FieldLinkedMessageID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(messagelink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MessageLinkUpsertOne) UpdateNewValues() *MessageLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(messagelink.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(messagelink.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MessageLinkUpsertOne) Ignore() *MessageLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageLinkUpsertOne) DoNothing() *MessageLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageLinkCreate.OnConflict
// documentation for more info.
func (u *MessageLinkUpsertOne) Update(set func(*MessageLinkUpsert)) *MessageLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetURL sets the "url" field.
func (u *MessageLinkUpsertOne) SetURL(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateURL() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *MessageLinkUpsertOne) SetTitle(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateTitle() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *MessageLinkUpsertOne) ClearTitle() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearTitle()
	})
}

// SetDescription sets the "description" field.
func (u *MessageLinkUpsertOne) SetDescription(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateDescription() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *MessageLinkUpsertOne) ClearDescription() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearDescription()
	})
}

// SetImageURL sets the "image_url" field.
func (u *MessageLinkUpsertOne) SetImageURL(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateImageURL() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageURL()
	})
}

// ClearImageURL clears the value of the "image_url" field.
func (u *MessageLinkUpsertOne) ClearImageURL() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageURL()
	})
}

// SetSiteName sets the "site_name" field.
func (u *MessageLinkUpsertOne) SetSiteName(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetSiteName(v)
	})
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateSiteName() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateSiteName()
	})
}

// ClearSiteName clears the value of the "site_name" field.
func (u *MessageLinkUpsertOne) ClearSiteName() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearSiteName()
	})
}

// SetCardType sets the "card_type" field.
func (u *MessageLinkUpsertOne) SetCardType(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetCardType(v)
	})
}

// UpdateCardType sets the "card_type" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateCardType() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateCardType()
	})
}

// ClearCardType clears the value of the "card_type" field.
func (u *MessageLinkUpsertOne) ClearCardType() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearCardType()
	})
}

// SetImageWidth sets the "image_width" field.
func (u *MessageLinkUpsertOne) SetImageWidth(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageWidth(v)
	})
}

// AddImageWidth adds v to the "image_width" field.
func (u *MessageLinkUpsertOne) AddImageWidth(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddImageWidth(v)
	})
}

// UpdateImageWidth sets the "image_width" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateImageWidth() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageWidth()
	})
}

// ClearImageWidth clears the value of the "image_width" field.
func (u *MessageLinkUpsertOne) ClearImageWidth() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageWidth()
	})
}

// SetImageHeight sets the "image_height" field.
func (u *MessageLinkUpsertOne) SetImageHeight(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageHeight(v)
	})
}

// AddImageHeight adds v to the "image_height" field.
func (u *MessageLinkUpsertOne) AddImageHeight(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddImageHeight(v)
	})
}

// UpdateImageHeight sets the "image_height" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateImageHeight() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageHeight()
	})
}

// ClearImageHeight clears the value of the "image_height" field.
func (u *MessageLinkUpsertOne) ClearImageHeight() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageHeight()
	})
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (u *MessageLinkUpsertOne) SetYoutubeVideoID(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeVideoID(v)
	})
}

// UpdateYoutubeVideoID sets the "youtube_video_id" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateYoutubeVideoID() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeVideoID()
	})
}

// ClearYoutubeVideoID clears the value of the "youtube_video_id" field.
func (u *MessageLinkUpsertOne) ClearYoutubeVideoID() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeVideoID()
	})
}

// SetYoutubeChannelName sets the "youtube_channel_name" field.
func (u *MessageLinkUpsertOne) SetYoutubeChannelName(v string) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeChannelName(v)
	})
}

// UpdateYoutubeChannelName sets the "youtube_channel_name" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateYoutubeChannelName() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeChannelName()
	})
}

// ClearYoutubeChannelName clears the value of the "youtube_channel_name" field.
func (u *MessageLinkUpsertOne) ClearYoutubeChannelName() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeChannelName()
	})
}

// SetYoutubeDurationSeconds sets the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertOne) SetYoutubeDurationSeconds(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeDurationSeconds(v)
	})
}

// AddYoutubeDurationSeconds adds v to the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertOne) AddYoutubeDurationSeconds(v int32) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddYoutubeDurationSeconds(v)
	})
}

// UpdateYoutubeDurationSeconds sets the "youtube_duration_seconds" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateYoutubeDurationSeconds() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeDurationSeconds()
	})
}

// ClearYoutubeDurationSeconds clears the value of the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertOne) ClearYoutubeDurationSeconds() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeDurationSeconds()
	})
}

// SetLinkedMessageID sets the "linked_message_id" field.
func (u *MessageLinkUpsertOne) SetLinkedMessageID(v uuid.UUID) *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetLinkedMessageID(v)
	})
}

// UpdateLinkedMessageID sets the "linked_message_id" field to the value that was provided on create.
func (u *MessageLinkUpsertOne) UpdateLinkedMessageID() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateLinkedMessageID()
	})
}

// ClearLinkedMessageID clears the value of the "linked_message_id" field.
func (u *MessageLinkUpsertOne) ClearLinkedMessageID() *MessageLinkUpsertOne {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearLinkedMessageID()
	})
}

// Exec executes the query.
func (u *MessageLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageLinkUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MessageLinkUpsertOne.ID is not supported by MySQL driver. Use MessageLinkUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageLinkUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageLinkCreateBulk is the builder for creating many MessageLink entities in bulk.
type MessageLinkCreateBulk struct {
	config
	err      error
	builders []*MessageLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the MessageLink entities in the database.
func (_c *MessageLinkCreateBulk) Save(ctx context.Context) ([]*MessageLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MessageLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageLinkCreateBulk) SaveX(ctx context.Context) []*MessageLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageLinkUpsert) {
//			SetURL(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageLinkUpsertBulk {
	_c.conflict = opts
	return &MessageLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageLinkCreateBulk) OnConflictColumns(columns ...string) *MessageLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageLinkUpsertBulk{
		create: _c,
	}
}

// MessageLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of MessageLink nodes.
type MessageLinkUpsertBulk struct {
	create *MessageLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(messagelink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MessageLinkUpsertBulk) UpdateNewValues() *MessageLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(messagelink.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(messagelink.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MessageLinkUpsertBulk) Ignore() *MessageLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageLinkUpsertBulk) DoNothing() *MessageLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageLinkCreateBulk.OnConflict
// documentation for more info.
func (u *MessageLinkUpsertBulk) Update(set func(*MessageLinkUpsert)) *MessageLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetURL sets the "url" field.
func (u *MessageLinkUpsertBulk) SetURL(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateURL() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *MessageLinkUpsertBulk) SetTitle(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateTitle() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *MessageLinkUpsertBulk) ClearTitle() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearTitle()
	})
}

// SetDescription sets the "description" field.
func (u *MessageLinkUpsertBulk) SetDescription(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateDescription() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *MessageLinkUpsertBulk) ClearDescription() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearDescription()
	})
}

// SetImageURL sets the "image_url" field.
func (u *MessageLinkUpsertBulk) SetImageURL(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateImageURL() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageURL()
	})
}

// ClearImageURL clears the value of the "image_url" field.
func (u *MessageLinkUpsertBulk) ClearImageURL() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageURL()
	})
}

// SetSiteName sets the "site_name" field.
func (u *MessageLinkUpsertBulk) SetSiteName(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetSiteName(v)
	})
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateSiteName() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateSiteName()
	})
}

// ClearSiteName clears the value of the "site_name" field.
func (u *MessageLinkUpsertBulk) ClearSiteName() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearSiteName()
	})
}

// SetCardType sets the "card_type" field.
func (u *MessageLinkUpsertBulk) SetCardType(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetCardType(v)
	})
}

// UpdateCardType sets the "card_type" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateCardType() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateCardType()
	})
}

// ClearCardType clears the value of the "card_type" field.
func (u *MessageLinkUpsertBulk) ClearCardType() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearCardType()
	})
}

// SetImageWidth sets the "image_width" field.
func (u *MessageLinkUpsertBulk) SetImageWidth(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageWidth(v)
	})
}

// AddImageWidth adds v to the "image_width" field.
func (u *MessageLinkUpsertBulk) AddImageWidth(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddImageWidth(v)
	})
}

// UpdateImageWidth sets the "image_width" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateImageWidth() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageWidth()
	})
}

// ClearImageWidth clears the value of the "image_width" field.
func (u *MessageLinkUpsertBulk) ClearImageWidth() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageWidth()
	})
}

// SetImageHeight sets the "image_height" field.
func (u *MessageLinkUpsertBulk) SetImageHeight(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetImageHeight(v)
	})
}

// AddImageHeight adds v to the "image_height" field.
func (u *MessageLinkUpsertBulk) AddImageHeight(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddImageHeight(v)
	})
}

// UpdateImageHeight sets the "image_height" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateImageHeight() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateImageHeight()
	})
}

// ClearImageHeight clears the value of the "image_height" field.
func (u *MessageLinkUpsertBulk) ClearImageHeight() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearImageHeight()
	})
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (u *MessageLinkUpsertBulk) SetYoutubeVideoID(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeVideoID(v)
	})
}

// UpdateYoutubeVideoID sets the "youtube_video_id" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateYoutubeVideoID() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeVideoID()
	})
}

// ClearYoutubeVideoID clears the value of the "youtube_video_id" field.
func (u *MessageLinkUpsertBulk) ClearYoutubeVideoID() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeVideoID()
	})
}

// SetYoutubeChannelName sets the "youtube_channel_name" field.
func (u *MessageLinkUpsertBulk) SetYoutubeChannelName(v string) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeChannelName(v)
	})
}

// UpdateYoutubeChannelName sets the "youtube_channel_name" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateYoutubeChannelName() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeChannelName()
	})
}

// ClearYoutubeChannelName clears the value of the "youtube_channel_name" field.
func (u *MessageLinkUpsertBulk) ClearYoutubeChannelName() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeChannelName()
	})
}

// SetYoutubeDurationSeconds sets the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertBulk) SetYoutubeDurationSeconds(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetYoutubeDurationSeconds(v)
	})
}

// AddYoutubeDurationSeconds adds v to the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertBulk) AddYoutubeDurationSeconds(v int32) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.AddYoutubeDurationSeconds(v)
	})
}

// UpdateYoutubeDurationSeconds sets the "youtube_duration_seconds" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateYoutubeDurationSeconds() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateYoutubeDurationSeconds()
	})
}

// ClearYoutubeDurationSeconds clears the value of the "youtube_duration_seconds" field.
func (u *MessageLinkUpsertBulk) ClearYoutubeDurationSeconds() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearYoutubeDurationSeconds()
	})
}

// SetLinkedMessageID sets the "linked_message_id" field.
func (u *MessageLinkUpsertBulk) SetLinkedMessageID(v uuid.UUID) *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.SetLinkedMessageID(v)
	})
}

// UpdateLinkedMessageID sets the "linked_message_id" field to the value that was provided on create.
func (u *MessageLinkUpsertBulk) UpdateLinkedMessageID() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.UpdateLinkedMessageID()
	})
}

// ClearLinkedMessageID clears the value of the "linked_message_id" field.
func (u *MessageLinkUpsertBulk) ClearLinkedMessageID() *MessageLinkUpsertBulk {
	return u.Update(func(s *MessageLinkUpsert) {
		s.ClearLinkedMessageID()
	})
}

// Exec executes the query.
func (u *MessageLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MessageLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
