// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/message"
	"github.com/newt239/chat/ent/messagepin"
	"github.com/newt239/chat/ent/user"
)

// MessagePin is the model entity for the MessagePin schema.
type MessagePin struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessagePinQuery when eager-loading is set.
	Edges                 MessagePinEdges `json:"edges"`
	message_pin_channel   *uuid.UUID
	message_pin_message   *uuid.UUID
	message_pin_pinned_by *uuid.UUID
	selectValues          sql.SelectValues
}

// MessagePinEdges holds the relations/edges for other nodes in the graph.
type MessagePinEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// PinnedBy holds the value of the pinned_by edge.
	PinnedBy *User `json:"pinned_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessagePinEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessagePinEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// PinnedByOrErr returns the PinnedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessagePinEdges) PinnedByOrErr() (*User, error) {
	if e.PinnedBy != nil {
		return e.PinnedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "pinned_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessagePin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messagepin.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case messagepin.FieldID:
			values[i] = new(uuid.UUID)
		case messagepin.ForeignKeys[0]: // message_pin_channel
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case messagepin.ForeignKeys[1]: // message_pin_message
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case messagepin.ForeignKeys[2]: // message_pin_pinned_by
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessagePin fields.
func (_m *MessagePin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messagepin.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case messagepin.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case messagepin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_pin_channel", values[i])
			} else if value.Valid {
				_m.message_pin_channel = new(uuid.UUID)
				*_m.message_pin_channel = *value.S.(*uuid.UUID)
			}
		case messagepin.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_pin_message", values[i])
			} else if value.Valid {
				_m.message_pin_message = new(uuid.UUID)
				*_m.message_pin_message = *value.S.(*uuid.UUID)
			}
		case messagepin.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_pin_pinned_by", values[i])
			} else if value.Valid {
				_m.message_pin_pinned_by = new(uuid.UUID)
				*_m.message_pin_pinned_by = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessagePin.
// This includes values selected through modifiers, order, etc.
func (_m *MessagePin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the MessagePin entity.
func (_m *MessagePin) QueryChannel() *ChannelQuery {
	return NewMessagePinClient(_m.config).QueryChannel(_m)
}

// QueryMessage queries the "message" edge of the MessagePin entity.
func (_m *MessagePin) QueryMessage() *MessageQuery {
	return NewMessagePinClient(_m.config).QueryMessage(_m)
}

// QueryPinnedBy queries the "pinned_by" edge of the MessagePin entity.
func (_m *MessagePin) QueryPinnedBy() *UserQuery {
	return NewMessagePinClient(_m.config).QueryPinnedBy(_m)
}

// Update returns a builder for updating this MessagePin.
// Note that you need to call MessagePin.Unwrap() before calling this method if this MessagePin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MessagePin) Update() *MessagePinUpdateOne {
	return NewMessagePinClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MessagePin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MessagePin) Unwrap() *MessagePin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessagePin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MessagePin) String() string {
	var builder strings.Builder
	builder.WriteString("MessagePin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MessagePins is a parsable slice of MessagePin.
type MessagePins []*MessagePin
