// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/polloption"
	"github.com/newt239/chat/ent/pollvote"
	"github.com/newt239/chat/ent/user"
)

// PollVote is the model entity for the PollVote schema.
type PollVote struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OptionID holds the value of the "option_id" field.
	OptionID uuid.UUID `json:"option_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PollVoteQuery when eager-loading is set.
	Edges        PollVoteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PollVoteEdges holds the relations/edges for other nodes in the graph.
type PollVoteEdges struct {
	// Option holds the value of the option edge.
	Option *PollOption `json:"option,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OptionOrErr returns the Option value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PollVoteEdges) OptionOrErr() (*PollOption, error) {
	if e.Option != nil {
		return e.Option, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: polloption.Label}
	}
	return nil, &NotLoadedError{edge: "option"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PollVoteEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PollVote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pollvote.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pollvote.FieldID, pollvote.FieldOptionID, pollvote.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PollVote fields.
func (_m *PollVote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pollvote.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pollvote.FieldOptionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field option_id", values[i])
			} else if value != nil {
				_m.OptionID = *value
			}
		case pollvote.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case pollvote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PollVote.
// This includes values selected through modifiers, order, etc.
func (_m *PollVote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOption queries the "option" edge of the PollVote entity.
func (_m *PollVote) QueryOption() *PollOptionQuery {
	return NewPollVoteClient(_m.config).QueryOption(_m)
}

// QueryUser queries the "user" edge of the PollVote entity.
func (_m *PollVote) QueryUser() *UserQuery {
	return NewPollVoteClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PollVote.
// Note that you need to call PollVote.Unwrap() before calling this method if this PollVote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PollVote) Update() *PollVoteUpdateOne {
	return NewPollVoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PollVote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PollVote) Unwrap() *PollVote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PollVote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PollVote) String() string {
	var builder strings.Builder
	builder.WriteString("PollVote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("option_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OptionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PollVotes is a parsable slice of PollVote.
type PollVotes []*PollVote
