// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/newt239/chat/ent/predicate"
	"github.com/newt239/chat/ent/scheduledmessage"
)

// ScheduledMessageDelete is the builder for deleting a ScheduledMessage entity.
type ScheduledMessageDelete struct {
	config
	hooks    []Hook
	mutation *ScheduledMessageMutation
}

// Where appends a list predicates to the ScheduledMessageDelete builder.
func (_d *ScheduledMessageDelete) Where(ps ...predicate.ScheduledMessage) *ScheduledMessageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ScheduledMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScheduledMessageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ScheduledMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scheduledmessage.Table, sqlgraph.NewFieldSpec(scheduledmessage.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ScheduledMessageDeleteOne is the builder for deleting a single ScheduledMessage entity.
type ScheduledMessageDeleteOne struct {
	_d *ScheduledMessageDelete
}

// Where appends a list predicates to the ScheduledMessageDelete builder.
func (_d *ScheduledMessageDeleteOne) Where(ps ...predicate.ScheduledMessage) *ScheduledMessageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ScheduledMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scheduledmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScheduledMessageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
