// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/predicate"
	"github.com/newt239/chat/ent/systemmessage"
	"github.com/newt239/chat/ent/user"
)

// SystemMessageUpdate is the builder for updating SystemMessage entities.
type SystemMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SystemMessageMutation
}

// Where appends a list predicates to the SystemMessageUpdate builder.
func (_u *SystemMessageUpdate) Where(ps ...predicate.SystemMessage) *SystemMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SystemMessageUpdate) SetKind(v string) *SystemMessageUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SystemMessageUpdate) SetNillableKind(v *string) *SystemMessageUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SystemMessageUpdate) SetPayload(v map[string]interface{}) *SystemMessageUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *SystemMessageUpdate) SetChannelID(id uuid.UUID) *SystemMessageUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *SystemMessageUpdate) SetChannel(v *Channel) *SystemMessageUpdate {
	return _u.SetChannelID(v.ID)
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_u *SystemMessageUpdate) SetActorID(id uuid.UUID) *SystemMessageUpdate {
	_u.mutation.SetActorID(id)
	return _u
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_u *SystemMessageUpdate) SetNillableActorID(id *uuid.UUID) *SystemMessageUpdate {
	if id != nil {
		_u = _u.SetActorID(*id)
	}
	return _u
}

// SetActor sets the "actor" edge to the User entity.
func (_u *SystemMessageUpdate) SetActor(v *User) *SystemMessageUpdate {
	return _u.SetActorID(v.ID)
}

// Mutation returns the SystemMessageMutation object of the builder.
func (_u *SystemMessageUpdate) Mutation() *SystemMessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *SystemMessageUpdate) ClearChannel() *SystemMessageUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *SystemMessageUpdate) ClearActor() *SystemMessageUpdate {
	_u.mutation.ClearActor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemMessageUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := systemmessage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SystemMessage.kind": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemMessage.channel"`)
	}
	return nil
}

func (_u *SystemMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemmessage.Table, systemmessage.Columns, sqlgraph.NewFieldSpec(systemmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(systemmessage.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(systemmessage.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ChannelTable,
			Columns: []string{systemmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ChannelTable,
			Columns: []string{systemmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ActorTable,
			Columns: []string{systemmessage.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ActorTable,
			Columns: []string{systemmessage.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemMessageUpdateOne is the builder for updating a single SystemMessage entity.
type SystemMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemMessageMutation
}

// SetKind sets the "kind" field.
func (_u *SystemMessageUpdateOne) SetKind(v string) *SystemMessageUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SystemMessageUpdateOne) SetNillableKind(v *string) *SystemMessageUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SystemMessageUpdateOne) SetPayload(v map[string]interface{}) *SystemMessageUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *SystemMessageUpdateOne) SetChannelID(id uuid.UUID) *SystemMessageUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *SystemMessageUpdateOne) SetChannel(v *Channel) *SystemMessageUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_u *SystemMessageUpdateOne) SetActorID(id uuid.UUID) *SystemMessageUpdateOne {
	_u.mutation.SetActorID(id)
	return _u
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_u *SystemMessageUpdateOne) SetNillableActorID(id *uuid.UUID) *SystemMessageUpdateOne {
	if id != nil {
		_u = _u.SetActorID(*id)
	}
	return _u
}

// SetActor sets the "actor" edge to the User entity.
func (_u *SystemMessageUpdateOne) SetActor(v *User) *SystemMessageUpdateOne {
	return _u.SetActorID(v.ID)
}

// Mutation returns the SystemMessageMutation object of the builder.
func (_u *SystemMessageUpdateOne) Mutation() *SystemMessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *SystemMessageUpdateOne) ClearChannel() *SystemMessageUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *SystemMessageUpdateOne) ClearActor() *SystemMessageUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// Where appends a list predicates to the SystemMessageUpdate builder.
func (_u *SystemMessageUpdateOne) Where(ps ...predicate.SystemMessage) *SystemMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemMessageUpdateOne) Select(field string, fields ...string) *SystemMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemMessage entity.
func (_u *SystemMessageUpdateOne) Save(ctx context.Context) (*SystemMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemMessageUpdateOne) SaveX(ctx context.Context) *SystemMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := systemmessage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SystemMessage.kind": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemMessage.channel"`)
	}
	return nil
}

func (_u *SystemMessageUpdateOne) sqlSave(ctx context.Context) (_node *SystemMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemmessage.Table, systemmessage.Columns, sqlgraph.NewFieldSpec(systemmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemmessage.FieldID)
		for _, f := range fields {
			if !systemmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(systemmessage.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(systemmessage.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ChannelTable,
			Columns: []string{systemmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ChannelTable,
			Columns: []string{systemmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ActorTable,
			Columns: []string{systemmessage.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systemmessage.ActorTable,
			Columns: []string{systemmessage.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
