// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/message"
	"github.com/newt239/chat/ent/threadmetadata"
	"github.com/newt239/chat/ent/user"
)

// ThreadMetadata is the model entity for the ThreadMetadata schema.
type ThreadMetadata struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ReplyCount holds the value of the "reply_count" field.
	ReplyCount int `json:"reply_count,omitempty"`
	// LastReplyAt holds the value of the "last_reply_at" field.
	LastReplyAt time.Time `json:"last_reply_at,omitempty"`
	// ParticipantUserIds holds the value of the "participant_user_ids" field.
	ParticipantUserIds []uuid.UUID `json:"participant_user_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThreadMetadataQuery when eager-loading is set.
	Edges                           ThreadMetadataEdges `json:"edges"`
	thread_metadata_message         *uuid.UUID
	thread_metadata_last_reply_user *uuid.UUID
	selectValues                    sql.SelectValues
}

// ThreadMetadataEdges holds the relations/edges for other nodes in the graph.
type ThreadMetadataEdges struct {
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// LastReplyUser holds the value of the last_reply_user edge.
	LastReplyUser *User `json:"last_reply_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadMetadataEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// LastReplyUserOrErr returns the LastReplyUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadMetadataEdges) LastReplyUserOrErr() (*User, error) {
	if e.LastReplyUser != nil {
		return e.LastReplyUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "last_reply_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ThreadMetadata) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case threadmetadata.FieldParticipantUserIds:
			values[i] = new([]byte)
		case threadmetadata.FieldReplyCount:
			values[i] = new(sql.NullInt64)
		case threadmetadata.FieldLastReplyAt, threadmetadata.FieldCreatedAt, threadmetadata.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case threadmetadata.FieldID:
			values[i] = new(uuid.UUID)
		case threadmetadata.ForeignKeys[0]: // thread_metadata_message
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case threadmetadata.ForeignKeys[1]: // thread_metadata_last_reply_user
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ThreadMetadata fields.
func (_m *ThreadMetadata) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case threadmetadata.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case threadmetadata.FieldReplyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reply_count", values[i])
			} else if value.Valid {
				_m.ReplyCount = int(value.Int64)
			}
		case threadmetadata.FieldLastReplyAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_reply_at", values[i])
			} else if value.Valid {
				_m.LastReplyAt = value.Time
			}
		case threadmetadata.FieldParticipantUserIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field participant_user_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParticipantUserIds); err != nil {
					return fmt.Errorf("unmarshal field participant_user_ids: %w", err)
				}
			}
		case threadmetadata.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case threadmetadata.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case threadmetadata.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field thread_metadata_message", values[i])
			} else if value.Valid {
				_m.thread_metadata_message = new(uuid.UUID)
				*_m.thread_metadata_message = *value.S.(*uuid.UUID)
			}
		case threadmetadata.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field thread_metadata_last_reply_user", values[i])
			} else if value.Valid {
				_m.thread_metadata_last_reply_user = new(uuid.UUID)
				*_m.thread_metadata_last_reply_user = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ThreadMetadata.
// This includes values selected through modifiers, order, etc.
func (_m *ThreadMetadata) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the ThreadMetadata entity.
func (_m *ThreadMetadata) QueryMessage() *MessageQuery {
	return NewThreadMetadataClient(_m.config).QueryMessage(_m)
}

// QueryLastReplyUser queries the "last_reply_user" edge of the ThreadMetadata entity.
func (_m *ThreadMetadata) QueryLastReplyUser() *UserQuery {
	return NewThreadMetadataClient(_m.config).QueryLastReplyUser(_m)
}

// Update returns a builder for updating this ThreadMetadata.
// Note that you need to call ThreadMetadata.Unwrap() before calling this method if this ThreadMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ThreadMetadata) Update() *ThreadMetadataUpdateOne {
	return NewThreadMetadataClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ThreadMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ThreadMetadata) Unwrap() *ThreadMetadata {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ThreadMetadata is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ThreadMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("ThreadMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reply_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReplyCount))
	builder.WriteString(", ")
	builder.WriteString("last_reply_at=")
	builder.WriteString(_m.LastReplyAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("participant_user_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParticipantUserIds))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ThreadMetadataSlice is a parsable slice of ThreadMetadata.
type ThreadMetadataSlice []*ThreadMetadata
