// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/user"
	"github.com/newt239/chat/ent/usergroup"
	"github.com/newt239/chat/ent/usergroupmember"
)

// UserGroupMember is the model entity for the UserGroupMember schema.
type UserGroupMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserGroupMemberQuery when eager-loading is set.
	Edges                   UserGroupMemberEdges `json:"edges"`
	user_group_member_group *uuid.UUID
	user_group_member_user  *uuid.UUID
	selectValues            sql.SelectValues
}

// UserGroupMemberEdges holds the relations/edges for other nodes in the graph.
type UserGroupMemberEdges struct {
	// Group holds the value of the group edge.
	Group *UserGroup `json:"group,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupMemberEdges) GroupOrErr() (*UserGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usergroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usergroupmember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case usergroupmember.FieldID:
			values[i] = new(uuid.UUID)
		case usergroupmember.ForeignKeys[0]: // user_group_member_group
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case usergroupmember.ForeignKeys[1]: // user_group_member_user
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserGroupMember fields.
func (_m *UserGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usergroupmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case usergroupmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case usergroupmember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_group_member_group", values[i])
			} else if value.Valid {
				_m.user_group_member_group = new(uuid.UUID)
				*_m.user_group_member_group = *value.S.(*uuid.UUID)
			}
		case usergroupmember.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_group_member_user", values[i])
			} else if value.Valid {
				_m.user_group_member_user = new(uuid.UUID)
				*_m.user_group_member_user = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserGroupMember.
// This includes values selected through modifiers, order, etc.
func (_m *UserGroupMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the UserGroupMember entity.
func (_m *UserGroupMember) QueryGroup() *UserGroupQuery {
	return NewUserGroupMemberClient(_m.config).QueryGroup(_m)
}

// QueryUser queries the "user" edge of the UserGroupMember entity.
func (_m *UserGroupMember) QueryUser() *UserQuery {
	return NewUserGroupMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserGroupMember.
// Note that you need to call UserGroupMember.Unwrap() before calling this method if this UserGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserGroupMember) Update() *UserGroupMemberUpdateOne {
	return NewUserGroupMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserGroupMember) Unwrap() *UserGroupMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserGroupMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("UserGroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserGroupMembers is a parsable slice of UserGroupMember.
type UserGroupMembers []*UserGroupMember
