// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/user"
	"github.com/newt239/chat/ent/userpreference"
)

// UserPreference is the model entity for the UserPreference schema.
type UserPreference struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ThemeHue holds the value of the "theme_hue" field.
	ThemeHue int `json:"theme_hue,omitempty"`
	// ThemeChroma holds the value of the "theme_chroma" field.
	ThemeChroma float64 `json:"theme_chroma,omitempty"`
	// ThemeSidebar holds the value of the "theme_sidebar" field.
	ThemeSidebar userpreference.ThemeSidebar `json:"theme_sidebar,omitempty"`
	// ColorMode holds the value of the "color_mode" field.
	ColorMode userpreference.ColorMode `json:"color_mode,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// NotificationLevel holds the value of the "notification_level" field.
	NotificationLevel userpreference.NotificationLevel `json:"notification_level,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// TimezoneAutoUpdate holds the value of the "timezone_auto_update" field.
	TimezoneAutoUpdate bool `json:"timezone_auto_update,omitempty"`
	// ChannelSortOrder holds the value of the "channel_sort_order" field.
	ChannelSortOrder userpreference.ChannelSortOrder `json:"channel_sort_order,omitempty"`
	// HideJoinMessages holds the value of the "hide_join_messages" field.
	HideJoinMessages bool `json:"hide_join_messages,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserPreferenceQuery when eager-loading is set.
	Edges        UserPreferenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserPreferenceEdges holds the relations/edges for other nodes in the graph.
type UserPreferenceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPreferenceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPreference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpreference.FieldTimezoneAutoUpdate, userpreference.FieldHideJoinMessages:
			values[i] = new(sql.NullBool)
		case userpreference.FieldThemeChroma:
			values[i] = new(sql.NullFloat64)
		case userpreference.FieldThemeHue:
			values[i] = new(sql.NullInt64)
		case userpreference.FieldThemeSidebar, userpreference.FieldColorMode, userpreference.FieldLocale, userpreference.FieldNotificationLevel, userpreference.FieldTimezone, userpreference.FieldChannelSortOrder:
			values[i] = new(sql.NullString)
		case userpreference.FieldID, userpreference.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPreference fields.
func (_m *UserPreference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpreference.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case userpreference.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case userpreference.FieldThemeHue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field theme_hue", values[i])
			} else if value.Valid {
				_m.ThemeHue = int(value.Int64)
			}
		case userpreference.FieldThemeChroma:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field theme_chroma", values[i])
			} else if value.Valid {
				_m.ThemeChroma = value.Float64
			}
		case userpreference.FieldThemeSidebar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme_sidebar", values[i])
			} else if value.Valid {
				_m.ThemeSidebar = userpreference.ThemeSidebar(value.String)
			}
		case userpreference.FieldColorMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color_mode", values[i])
			} else if value.Valid {
				_m.ColorMode = userpreference.ColorMode(value.String)
			}
		case userpreference.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case userpreference.FieldNotificationLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notification_level", values[i])
			} else if value.Valid {
				_m.NotificationLevel = userpreference.NotificationLevel(value.String)
			}
		case userpreference.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case userpreference.FieldTimezoneAutoUpdate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field timezone_auto_update", values[i])
			} else if value.Valid {
				_m.TimezoneAutoUpdate = value.Bool
			}
		case userpreference.FieldChannelSortOrder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_sort_order", values[i])
			} else if value.Valid {
				_m.ChannelSortOrder = userpreference.ChannelSortOrder(value.String)
			}
		case userpreference.FieldHideJoinMessages:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hide_join_messages", values[i])
			} else if value.Valid {
				_m.HideJoinMessages = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPreference.
// This includes values selected through modifiers, order, etc.
func (_m *UserPreference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserPreference entity.
func (_m *UserPreference) QueryUser() *UserQuery {
	return NewUserPreferenceClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserPreference.
// Note that you need to call UserPreference.Unwrap() before calling this method if this UserPreference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPreference) Update() *UserPreferenceUpdateOne {
	return NewUserPreferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPreference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPreference) Unwrap() *UserPreference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPreference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPreference) String() string {
	var builder strings.Builder
	builder.WriteString("UserPreference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("theme_hue=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThemeHue))
	builder.WriteString(", ")
	builder.WriteString("theme_chroma=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThemeChroma))
	builder.WriteString(", ")
	builder.WriteString("theme_sidebar=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThemeSidebar))
	builder.WriteString(", ")
	builder.WriteString("color_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.ColorMode))
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("notification_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationLevel))
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("timezone_auto_update=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimezoneAutoUpdate))
	builder.WriteString(", ")
	builder.WriteString("channel_sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelSortOrder))
	builder.WriteString(", ")
	builder.WriteString("hide_join_messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.HideJoinMessages))
	builder.WriteByte(')')
	return builder.String()
}

// UserPreferences is a parsable slice of UserPreference.
type UserPreferences []*UserPreference
