// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/channel"
	"github.com/newt239/chat/ent/user"
	"github.com/newt239/chat/ent/webhook"
)

// WebhookCreate is the builder for creating a Webhook entity.
type WebhookCreate struct {
	config
	mutation *WebhookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *WebhookCreate) SetName(v string) *WebhookCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *WebhookCreate) SetAvatarURL(v string) *WebhookCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableAvatarURL(v *string) *WebhookCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *WebhookCreate) SetTokenHash(v string) *WebhookCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *WebhookCreate) SetLastUsedAt(v time.Time) *WebhookCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableLastUsedAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookCreate) SetCreatedAt(v time.Time) *WebhookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableCreatedAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookCreate) SetUpdatedAt(v time.Time) *WebhookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableUpdatedAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WebhookCreate) SetID(v uuid.UUID) *WebhookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableID(v *uuid.UUID) *WebhookCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_c *WebhookCreate) SetChannelID(id uuid.UUID) *WebhookCreate {
	_c.mutation.SetChannelID(id)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *WebhookCreate) SetChannel(v *Channel) *WebhookCreate {
	return _c.SetChannelID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *WebhookCreate) SetCreatedByID(id uuid.UUID) *WebhookCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *WebhookCreate) SetCreatedBy(v *User) *WebhookCreate {
	return _c.SetCreatedByID(v.ID)
}

// SetBotUserID sets the "bot_user" edge to the User entity by ID.
func (_c *WebhookCreate) SetBotUserID(id uuid.UUID) *WebhookCreate {
	_c.mutation.SetBotUserID(id)
	return _c
}

// SetBotUser sets the "bot_user" edge to the User entity.
func (_c *WebhookCreate) SetBotUser(v *User) *WebhookCreate {
	return _c.SetBotUserID(v.ID)
}

// Mutation returns the WebhookMutation object of the builder.
func (_c *WebhookCreate) Mutation() *WebhookMutation {
	return _c.mutation
}

// Save creates the Webhook in the database.
func (_c *WebhookCreate) Save(ctx context.Context) (*Webhook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookCreate) SaveX(ctx context.Context) *Webhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webhook.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := webhook.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Webhook.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "Webhook.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := webhook.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Webhook.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Webhook.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Webhook.updated_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "Webhook.channel"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "Webhook.created_by"`)}
	}
	if len(_c.mutation.BotUserIDs()) == 0 {
		return &ValidationError{Name: "bot_user", err: errors.New(`ent: missing required edge "Webhook.bot_user"`)}
	}
	return nil
}

func (_c *WebhookCreate) sqlSave(ctx context.Context) (*Webhook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookCreate) createSpec() (*Webhook, *sqlgraph.CreateSpec) {
	var (
		_node = &Webhook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhook.Table, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(webhook.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(webhook.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(webhook.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   webhook.ChannelTable,
			Columns: []string{webhook.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.webhook_channel = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   webhook.CreatedByTable,
			Columns: []string{webhook.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.webhook_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BotUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   webhook.BotUserTable,
			Columns: []string{webhook.BotUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.webhook_bot_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Webhook.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *WebhookCreate) OnConflict(opts ...sql.ConflictOption) *WebhookUpsertOne {
	_c.conflict = opts
	return &WebhookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Webhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebhookCreate) OnConflictColumns(columns ...string) *WebhookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebhookUpsertOne{
		create: _c,
	}
}

type (
	// WebhookUpsertOne is the builder for "upsert"-ing
	//  one Webhook node.
	WebhookUpsertOne struct {
		create *WebhookCreate
	}

	// WebhookUpsert is the "OnConflict" setter.
	WebhookUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *WebhookUpsert) SetName(v string) *WebhookUpsert {
	u.Set(webhook.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebhookUpsert) UpdateName() *WebhookUpsert {
	u.SetExcluded(webhook.FieldName)
	return u
}

// SetAvatarURL sets the "avatar_url" field.
func (u *WebhookUpsert) SetAvatarURL(v string) *WebhookUpsert {
	u.Set(webhook.FieldAvatarURL, v)
	return u
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *WebhookUpsert) UpdateAvatarURL() *WebhookUpsert {
	u.SetExcluded(webhook.FieldAvatarURL)
	return u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *WebhookUpsert) ClearAvatarURL() *WebhookUpsert {
	u.SetNull(webhook.FieldAvatarURL)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *WebhookUpsert) SetTokenHash(v string) *WebhookUpsert {
	u.Set(webhook.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WebhookUpsert) UpdateTokenHash() *WebhookUpsert {
	u.SetExcluded(webhook.FieldTokenHash)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *WebhookUpsert) SetLastUsedAt(v time.Time) *WebhookUpsert {
	u.Set(webhook.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *WebhookUpsert) UpdateLastUsedAt() *WebhookUpsert {
	u.SetExcluded(webhook.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *WebhookUpsert) ClearLastUsedAt() *WebhookUpsert {
	u.SetNull(webhook.FieldLastUsedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookUpsert) SetUpdatedAt(v time.Time) *WebhookUpsert {
	u.Set(webhook.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookUpsert) UpdateUpdatedAt() *WebhookUpsert {
	u.SetExcluded(webhook.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Webhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(webhook.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WebhookUpsertOne) UpdateNewValues() *WebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(webhook.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webhook.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Webhook.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebhookUpsertOne) Ignore() *WebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebhookUpsertOne) DoNothing() *WebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebhookCreate.OnConflict
// documentation for more info.
func (u *WebhookUpsertOne) Update(set func(*WebhookUpsert)) *WebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *WebhookUpsertOne) SetName(v string) *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebhookUpsertOne) UpdateName() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *WebhookUpsertOne) SetAvatarURL(v string) *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *WebhookUpsertOne) UpdateAvatarURL() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateAvatarURL()
	})
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *WebhookUpsertOne) ClearAvatarURL() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.ClearAvatarURL()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *WebhookUpsertOne) SetTokenHash(v string) *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WebhookUpsertOne) UpdateTokenHash() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateTokenHash()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *WebhookUpsertOne) SetLastUsedAt(v time.Time) *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *WebhookUpsertOne) UpdateLastUsedAt() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *WebhookUpsertOne) ClearLastUsedAt() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookUpsertOne) SetUpdatedAt(v time.Time) *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookUpsertOne) UpdateUpdatedAt() *WebhookUpsertOne {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WebhookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebhookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebhookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebhookUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WebhookUpsertOne.ID is not supported by MySQL driver. Use WebhookUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebhookUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebhookCreateBulk is the builder for creating many Webhook entities in bulk.
type WebhookCreateBulk struct {
	config
	err      error
	builders []*WebhookCreate
	conflict []sql.ConflictOption
}

// Save creates the Webhook entities in the database.
func (_c *WebhookCreateBulk) Save(ctx context.Context) ([]*Webhook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Webhook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookCreateBulk) SaveX(ctx context.Context) []*Webhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Webhook.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *WebhookCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebhookUpsertBulk {
	_c.conflict = opts
	return &WebhookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Webhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebhookCreateBulk) OnConflictColumns(columns ...string) *WebhookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebhookUpsertBulk{
		create: _c,
	}
}

// WebhookUpsertBulk is the builder for "upsert"-ing
// a bulk of Webhook nodes.
type WebhookUpsertBulk struct {
	create *WebhookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Webhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(webhook.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WebhookUpsertBulk) UpdateNewValues() *WebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(webhook.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webhook.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Webhook.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebhookUpsertBulk) Ignore() *WebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebhookUpsertBulk) DoNothing() *WebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebhookCreateBulk.OnConflict
// documentation for more info.
func (u *WebhookUpsertBulk) Update(set func(*WebhookUpsert)) *WebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *WebhookUpsertBulk) SetName(v string) *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WebhookUpsertBulk) UpdateName() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *WebhookUpsertBulk) SetAvatarURL(v string) *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *WebhookUpsertBulk) UpdateAvatarURL() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateAvatarURL()
	})
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *WebhookUpsertBulk) ClearAvatarURL() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.ClearAvatarURL()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *WebhookUpsertBulk) SetTokenHash(v string) *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WebhookUpsertBulk) UpdateTokenHash() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateTokenHash()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *WebhookUpsertBulk) SetLastUsedAt(v time.Time) *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *WebhookUpsertBulk) UpdateLastUsedAt() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *WebhookUpsertBulk) ClearLastUsedAt() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookUpsertBulk) SetUpdatedAt(v time.Time) *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookUpsertBulk) UpdateUpdatedAt() *WebhookUpsertBulk {
	return u.Update(func(s *WebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WebhookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebhookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebhookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebhookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
