/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppRouteRouteImport } from "./routes/app/route";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as AppIndexRouteImport } from "./routes/app/index";
import { Route as AppWorkspaceIdRouteRouteImport } from "./routes/app/$workspaceId/route";
import { Route as DevUiRouteImport } from "./routes/dev/ui";
import { Route as AppWorkspaceIdIndexRouteImport } from "./routes/app/$workspaceId/index";
import { Route as AppWorkspaceIdChannelIdRouteImport } from "./routes/app/$workspaceId/$channelId";
import { Route as AppWorkspaceIdAdminRouteImport } from "./routes/app/$workspaceId/admin";
import { Route as AppWorkspaceIdInsightsRouteImport } from "./routes/app/$workspaceId/insights";
import { Route as AppWorkspaceIdSearchRouteImport } from "./routes/app/$workspaceId/search";
import { Route as AppWorkspaceIdThreadsRouteImport } from "./routes/app/$workspaceId/threads";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppWorkspaceIdRouteRoute = AppWorkspaceIdRouteRouteImport.update({
  id: "/$workspaceId",
  path: "/$workspaceId",
  getParentRoute: () => AppRouteRoute,
} as any);
const DevUiRoute = DevUiRouteImport.update({
  id: "/dev/ui",
  path: "/dev/ui",
  getParentRoute: () => rootRouteImport,
} as any);
const AppWorkspaceIdIndexRoute = AppWorkspaceIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);
const AppWorkspaceIdChannelIdRoute = AppWorkspaceIdChannelIdRouteImport.update({
  id: "/$channelId",
  path: "/$channelId",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);
const AppWorkspaceIdAdminRoute = AppWorkspaceIdAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);
const AppWorkspaceIdInsightsRoute = AppWorkspaceIdInsightsRouteImport.update({
  id: "/insights",
  path: "/insights",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);
const AppWorkspaceIdSearchRoute = AppWorkspaceIdSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);
const AppWorkspaceIdThreadsRoute = AppWorkspaceIdThreadsRouteImport.update({
  id: "/threads",
  path: "/threads",
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/app/$workspaceId": typeof AppWorkspaceIdRouteRouteWithChildren;
  "/dev/ui": typeof DevUiRoute;
  "/app/": typeof AppIndexRoute;
  "/app/$workspaceId/$channelId": typeof AppWorkspaceIdChannelIdRoute;
  "/app/$workspaceId/admin": typeof AppWorkspaceIdAdminRoute;
  "/app/$workspaceId/insights": typeof AppWorkspaceIdInsightsRoute;
  "/app/$workspaceId/search": typeof AppWorkspaceIdSearchRoute;
  "/app/$workspaceId/threads": typeof AppWorkspaceIdThreadsRoute;
  "/app/$workspaceId/": typeof AppWorkspaceIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/dev/ui": typeof DevUiRoute;
  "/app": typeof AppIndexRoute;
  "/app/$workspaceId/$channelId": typeof AppWorkspaceIdChannelIdRoute;
  "/app/$workspaceId/admin": typeof AppWorkspaceIdAdminRoute;
  "/app/$workspaceId/insights": typeof AppWorkspaceIdInsightsRoute;
  "/app/$workspaceId/search": typeof AppWorkspaceIdSearchRoute;
  "/app/$workspaceId/threads": typeof AppWorkspaceIdThreadsRoute;
  "/app/$workspaceId": typeof AppWorkspaceIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/app/$workspaceId": typeof AppWorkspaceIdRouteRouteWithChildren;
  "/dev/ui": typeof DevUiRoute;
  "/app/": typeof AppIndexRoute;
  "/app/$workspaceId/$channelId": typeof AppWorkspaceIdChannelIdRoute;
  "/app/$workspaceId/admin": typeof AppWorkspaceIdAdminRoute;
  "/app/$workspaceId/insights": typeof AppWorkspaceIdInsightsRoute;
  "/app/$workspaceId/search": typeof AppWorkspaceIdSearchRoute;
  "/app/$workspaceId/threads": typeof AppWorkspaceIdThreadsRoute;
  "/app/$workspaceId/": typeof AppWorkspaceIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/$workspaceId"
    | "/dev/ui"
    | "/app/"
    | "/app/$workspaceId/$channelId"
    | "/app/$workspaceId/admin"
    | "/app/$workspaceId/insights"
    | "/app/$workspaceId/search"
    | "/app/$workspaceId/threads"
    | "/app/$workspaceId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/register"
    | "/dev/ui"
    | "/app"
    | "/app/$workspaceId/$channelId"
    | "/app/$workspaceId/admin"
    | "/app/$workspaceId/insights"
    | "/app/$workspaceId/search"
    | "/app/$workspaceId/threads"
    | "/app/$workspaceId";
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/$workspaceId"
    | "/dev/ui"
    | "/app/"
    | "/app/$workspaceId/$channelId"
    | "/app/$workspaceId/admin"
    | "/app/$workspaceId/insights"
    | "/app/$workspaceId/search"
    | "/app/$workspaceId/threads"
    | "/app/$workspaceId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  DevUiRoute: typeof DevUiRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/": {
      id: "/app/";
      path: "/";
      fullPath: "/app/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/$workspaceId": {
      id: "/app/$workspaceId";
      path: "/$workspaceId";
      fullPath: "/app/$workspaceId";
      preLoaderRoute: typeof AppWorkspaceIdRouteRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/dev/ui": {
      id: "/dev/ui";
      path: "/dev/ui";
      fullPath: "/dev/ui";
      preLoaderRoute: typeof DevUiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/$workspaceId/": {
      id: "/app/$workspaceId/";
      path: "/";
      fullPath: "/app/$workspaceId/";
      preLoaderRoute: typeof AppWorkspaceIdIndexRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
    "/app/$workspaceId/$channelId": {
      id: "/app/$workspaceId/$channelId";
      path: "/$channelId";
      fullPath: "/app/$workspaceId/$channelId";
      preLoaderRoute: typeof AppWorkspaceIdChannelIdRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
    "/app/$workspaceId/admin": {
      id: "/app/$workspaceId/admin";
      path: "/admin";
      fullPath: "/app/$workspaceId/admin";
      preLoaderRoute: typeof AppWorkspaceIdAdminRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
    "/app/$workspaceId/insights": {
      id: "/app/$workspaceId/insights";
      path: "/insights";
      fullPath: "/app/$workspaceId/insights";
      preLoaderRoute: typeof AppWorkspaceIdInsightsRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
    "/app/$workspaceId/search": {
      id: "/app/$workspaceId/search";
      path: "/search";
      fullPath: "/app/$workspaceId/search";
      preLoaderRoute: typeof AppWorkspaceIdSearchRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
    "/app/$workspaceId/threads": {
      id: "/app/$workspaceId/threads";
      path: "/threads";
      fullPath: "/app/$workspaceId/threads";
      preLoaderRoute: typeof AppWorkspaceIdThreadsRouteImport;
      parentRoute: typeof AppWorkspaceIdRouteRoute;
    };
  }
}

interface AppWorkspaceIdRouteRouteChildren {
  AppWorkspaceIdChannelIdRoute: typeof AppWorkspaceIdChannelIdRoute;
  AppWorkspaceIdAdminRoute: typeof AppWorkspaceIdAdminRoute;
  AppWorkspaceIdInsightsRoute: typeof AppWorkspaceIdInsightsRoute;
  AppWorkspaceIdSearchRoute: typeof AppWorkspaceIdSearchRoute;
  AppWorkspaceIdThreadsRoute: typeof AppWorkspaceIdThreadsRoute;
  AppWorkspaceIdIndexRoute: typeof AppWorkspaceIdIndexRoute;
}

const AppWorkspaceIdRouteRouteChildren: AppWorkspaceIdRouteRouteChildren = {
  AppWorkspaceIdChannelIdRoute: AppWorkspaceIdChannelIdRoute,
  AppWorkspaceIdAdminRoute: AppWorkspaceIdAdminRoute,
  AppWorkspaceIdInsightsRoute: AppWorkspaceIdInsightsRoute,
  AppWorkspaceIdSearchRoute: AppWorkspaceIdSearchRoute,
  AppWorkspaceIdThreadsRoute: AppWorkspaceIdThreadsRoute,
  AppWorkspaceIdIndexRoute: AppWorkspaceIdIndexRoute,
};

const AppWorkspaceIdRouteRouteWithChildren =
  AppWorkspaceIdRouteRoute._addFileChildren(AppWorkspaceIdRouteRouteChildren);

interface AppRouteRouteChildren {
  AppWorkspaceIdRouteRoute: typeof AppWorkspaceIdRouteRouteWithChildren;
  AppIndexRoute: typeof AppIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceIdRouteRoute: AppWorkspaceIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DevUiRoute: DevUiRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
