// Code generated by ent, DO NOT EDIT.

package threadmetadata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/newt239/chat/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLTE(FieldID, id))
}

// ReplyCount applies equality check predicate on the "reply_count" field. It's identical to ReplyCountEQ.
func ReplyCount(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldReplyCount, v))
}

// LastReplyAt applies equality check predicate on the "last_reply_at" field. It's identical to LastReplyAtEQ.
func LastReplyAt(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldLastReplyAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReplyCountEQ applies the EQ predicate on the "reply_count" field.
func ReplyCountEQ(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldReplyCount, v))
}

// ReplyCountNEQ applies the NEQ predicate on the "reply_count" field.
func ReplyCountNEQ(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNEQ(FieldReplyCount, v))
}

// ReplyCountIn applies the In predicate on the "reply_count" field.
func ReplyCountIn(vs ...int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIn(FieldReplyCount, vs...))
}

// ReplyCountNotIn applies the NotIn predicate on the "reply_count" field.
func ReplyCountNotIn(vs ...int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotIn(FieldReplyCount, vs...))
}

// ReplyCountGT applies the GT predicate on the "reply_count" field.
func ReplyCountGT(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGT(FieldReplyCount, v))
}

// ReplyCountGTE applies the GTE predicate on the "reply_count" field.
func ReplyCountGTE(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGTE(FieldReplyCount, v))
}

// ReplyCountLT applies the LT predicate on the "reply_count" field.
func ReplyCountLT(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLT(FieldReplyCount, v))
}

// ReplyCountLTE applies the LTE predicate on the "reply_count" field.
func ReplyCountLTE(v int) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLTE(FieldReplyCount, v))
}

// LastReplyAtEQ applies the EQ predicate on the "last_reply_at" field.
func LastReplyAtEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldLastReplyAt, v))
}

// LastReplyAtNEQ applies the NEQ predicate on the "last_reply_at" field.
func LastReplyAtNEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNEQ(FieldLastReplyAt, v))
}

// LastReplyAtIn applies the In predicate on the "last_reply_at" field.
func LastReplyAtIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIn(FieldLastReplyAt, vs...))
}

// LastReplyAtNotIn applies the NotIn predicate on the "last_reply_at" field.
func LastReplyAtNotIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotIn(FieldLastReplyAt, vs...))
}

// LastReplyAtGT applies the GT predicate on the "last_reply_at" field.
func LastReplyAtGT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGT(FieldLastReplyAt, v))
}

// LastReplyAtGTE applies the GTE predicate on the "last_reply_at" field.
func LastReplyAtGTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGTE(FieldLastReplyAt, v))
}

// LastReplyAtLT applies the LT predicate on the "last_reply_at" field.
func LastReplyAtLT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLT(FieldLastReplyAt, v))
}

// LastReplyAtLTE applies the LTE predicate on the "last_reply_at" field.
func LastReplyAtLTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLTE(FieldLastReplyAt, v))
}

// LastReplyAtIsNil applies the IsNil predicate on the "last_reply_at" field.
func LastReplyAtIsNil() predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIsNull(FieldLastReplyAt))
}

// LastReplyAtNotNil applies the NotNil predicate on the "last_reply_at" field.
func LastReplyAtNotNil() predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotNull(FieldLastReplyAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.ThreadMetadata {
	return predicate.ThreadMetadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLastReplyUser applies the HasEdge predicate on the "last_reply_user" edge.
func HasLastReplyUser() predicate.ThreadMetadata {
	return predicate.ThreadMetadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LastReplyUserTable, LastReplyUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLastReplyUserWith applies the HasEdge predicate on the "last_reply_user" edge with a given conditions (other predicates).
func HasLastReplyUserWith(preds ...predicate.User) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(func(s *sql.Selector) {
		step := newLastReplyUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ThreadMetadata) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ThreadMetadata) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ThreadMetadata) predicate.ThreadMetadata {
	return predicate.ThreadMetadata(sql.NotPredicates(p))
}
